/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AffiliateMembership from './AffiliateMembership';
import Metadata from './Metadata';

/**
 * The AffiliateMembershipListEnvelope model module.
 * @module model/AffiliateMembershipListEnvelope
 * @version 1.0.0
 */
class AffiliateMembershipListEnvelope {
    /**
     * Constructs a new <code>AffiliateMembershipListEnvelope</code>.
     * @alias module:model/AffiliateMembershipListEnvelope
     * @param data {Array.<module:model/AffiliateMembership>} 
     * @param metadata {module:model/Metadata} 
     */
    constructor(data, metadata) { 
        
        AffiliateMembershipListEnvelope.initialize(this, data, metadata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, metadata) { 
        obj['data'] = data;
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>AffiliateMembershipListEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AffiliateMembershipListEnvelope} obj Optional instance to populate.
     * @return {module:model/AffiliateMembershipListEnvelope} The populated <code>AffiliateMembershipListEnvelope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AffiliateMembershipListEnvelope();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [AffiliateMembership]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AffiliateMembershipListEnvelope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AffiliateMembershipListEnvelope</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AffiliateMembershipListEnvelope.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                AffiliateMembership.validateJSON(item);
            };
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          Metadata.validateJSON(data['metadata']);
        }

        return true;
    }


}

AffiliateMembershipListEnvelope.RequiredProperties = ["data", "metadata"];

/**
 * @member {Array.<module:model/AffiliateMembership>} data
 */
AffiliateMembershipListEnvelope.prototype['data'] = undefined;

/**
 * @member {module:model/Metadata} metadata
 */
AffiliateMembershipListEnvelope.prototype['metadata'] = undefined;






export default AffiliateMembershipListEnvelope;

