/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AffiliateAttribution model module.
 * @module model/AffiliateAttribution
 * @version 1.0.0
 */
class AffiliateAttribution {
    /**
     * Constructs a new <code>AffiliateAttribution</code>.
     * @alias module:model/AffiliateAttribution
     * @param referredUserId {String} 
     * @param programId {String} 
     * @param referrerId {String} 
     * @param referrerUserId {String} 
     * @param tenantId {String} 
     * @param signupSource {String} Signup hostname when assigned at signup; empty for an assignment made later.
     * @param createdAt {Date} Immutable assignment time; activity begins counting from this timestamp.
     * @param referralCode {String} 
     */
    constructor(referredUserId, programId, referrerId, referrerUserId, tenantId, signupSource, createdAt, referralCode) { 
        
        AffiliateAttribution.initialize(this, referredUserId, programId, referrerId, referrerUserId, tenantId, signupSource, createdAt, referralCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, referredUserId, programId, referrerId, referrerUserId, tenantId, signupSource, createdAt, referralCode) { 
        obj['referred_user_id'] = referredUserId;
        obj['program_id'] = programId;
        obj['referrer_id'] = referrerId;
        obj['referrer_user_id'] = referrerUserId;
        obj['tenant_id'] = tenantId;
        obj['signup_source'] = signupSource;
        obj['created_at'] = createdAt;
        obj['referral_code'] = referralCode;
    }

    /**
     * Constructs a <code>AffiliateAttribution</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AffiliateAttribution} obj Optional instance to populate.
     * @return {module:model/AffiliateAttribution} The populated <code>AffiliateAttribution</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AffiliateAttribution();

            if (data.hasOwnProperty('referred_user_id')) {
                obj['referred_user_id'] = ApiClient.convertToType(data['referred_user_id'], 'String');
            }
            if (data.hasOwnProperty('program_id')) {
                obj['program_id'] = ApiClient.convertToType(data['program_id'], 'String');
            }
            if (data.hasOwnProperty('referrer_id')) {
                obj['referrer_id'] = ApiClient.convertToType(data['referrer_id'], 'String');
            }
            if (data.hasOwnProperty('referrer_user_id')) {
                obj['referrer_user_id'] = ApiClient.convertToType(data['referrer_user_id'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('signup_source')) {
                obj['signup_source'] = ApiClient.convertToType(data['signup_source'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('referral_code')) {
                obj['referral_code'] = ApiClient.convertToType(data['referral_code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AffiliateAttribution</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AffiliateAttribution</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AffiliateAttribution.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['referred_user_id'] && !(typeof data['referred_user_id'] === 'string' || data['referred_user_id'] instanceof String)) {
            throw new Error("Expected the field `referred_user_id` to be a primitive type in the JSON string but got " + data['referred_user_id']);
        }
        // ensure the json data is a string
        if (data['program_id'] && !(typeof data['program_id'] === 'string' || data['program_id'] instanceof String)) {
            throw new Error("Expected the field `program_id` to be a primitive type in the JSON string but got " + data['program_id']);
        }
        // ensure the json data is a string
        if (data['referrer_id'] && !(typeof data['referrer_id'] === 'string' || data['referrer_id'] instanceof String)) {
            throw new Error("Expected the field `referrer_id` to be a primitive type in the JSON string but got " + data['referrer_id']);
        }
        // ensure the json data is a string
        if (data['referrer_user_id'] && !(typeof data['referrer_user_id'] === 'string' || data['referrer_user_id'] instanceof String)) {
            throw new Error("Expected the field `referrer_user_id` to be a primitive type in the JSON string but got " + data['referrer_user_id']);
        }
        // ensure the json data is a string
        if (data['tenant_id'] && !(typeof data['tenant_id'] === 'string' || data['tenant_id'] instanceof String)) {
            throw new Error("Expected the field `tenant_id` to be a primitive type in the JSON string but got " + data['tenant_id']);
        }
        // ensure the json data is a string
        if (data['signup_source'] && !(typeof data['signup_source'] === 'string' || data['signup_source'] instanceof String)) {
            throw new Error("Expected the field `signup_source` to be a primitive type in the JSON string but got " + data['signup_source']);
        }
        // ensure the json data is a string
        if (data['referral_code'] && !(typeof data['referral_code'] === 'string' || data['referral_code'] instanceof String)) {
            throw new Error("Expected the field `referral_code` to be a primitive type in the JSON string but got " + data['referral_code']);
        }

        return true;
    }


}

AffiliateAttribution.RequiredProperties = ["referred_user_id", "program_id", "referrer_id", "referrer_user_id", "tenant_id", "signup_source", "created_at", "referral_code"];

/**
 * @member {String} referred_user_id
 */
AffiliateAttribution.prototype['referred_user_id'] = undefined;

/**
 * @member {String} program_id
 */
AffiliateAttribution.prototype['program_id'] = undefined;

/**
 * @member {String} referrer_id
 */
AffiliateAttribution.prototype['referrer_id'] = undefined;

/**
 * @member {String} referrer_user_id
 */
AffiliateAttribution.prototype['referrer_user_id'] = undefined;

/**
 * @member {String} tenant_id
 */
AffiliateAttribution.prototype['tenant_id'] = undefined;

/**
 * Signup hostname when assigned at signup; empty for an assignment made later.
 * @member {String} signup_source
 */
AffiliateAttribution.prototype['signup_source'] = undefined;

/**
 * Immutable assignment time; activity begins counting from this timestamp.
 * @member {Date} created_at
 */
AffiliateAttribution.prototype['created_at'] = undefined;

/**
 * @member {String} referral_code
 */
AffiliateAttribution.prototype['referral_code'] = undefined;






export default AffiliateAttribution;

