/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AffiliateReferral from './AffiliateReferral';

/**
 * The AffiliateReferralReport model module.
 * @module model/AffiliateReferralReport
 * @version 1.0.0
 */
class AffiliateReferralReport {
    /**
     * Constructs a new <code>AffiliateReferralReport</code>.
     * @alias module:model/AffiliateReferralReport
     * @param date {Date} 
     * @param referrals {Array.<module:model/AffiliateReferral>} 
     * @param hasMore {Boolean} 
     */
    constructor(date, referrals, hasMore) { 
        
        AffiliateReferralReport.initialize(this, date, referrals, hasMore);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, referrals, hasMore) { 
        obj['date'] = date;
        obj['referrals'] = referrals;
        obj['has_more'] = hasMore;
    }

    /**
     * Constructs a <code>AffiliateReferralReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AffiliateReferralReport} obj Optional instance to populate.
     * @return {module:model/AffiliateReferralReport} The populated <code>AffiliateReferralReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AffiliateReferralReport();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('referrals')) {
                obj['referrals'] = ApiClient.convertToType(data['referrals'], [AffiliateReferral]);
            }
            if (data.hasOwnProperty('has_more')) {
                obj['has_more'] = ApiClient.convertToType(data['has_more'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AffiliateReferralReport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AffiliateReferralReport</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AffiliateReferralReport.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['referrals']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['referrals'])) {
                throw new Error("Expected the field `referrals` to be an array in the JSON data but got " + data['referrals']);
            }
            // validate the optional field `referrals` (array)
            for (const item of data['referrals']) {
                AffiliateReferral.validateJSON(item);
            };
        }

        return true;
    }


}

AffiliateReferralReport.RequiredProperties = ["date", "referrals", "has_more"];

/**
 * @member {Date} date
 */
AffiliateReferralReport.prototype['date'] = undefined;

/**
 * @member {Array.<module:model/AffiliateReferral>} referrals
 */
AffiliateReferralReport.prototype['referrals'] = undefined;

/**
 * @member {Boolean} has_more
 */
AffiliateReferralReport.prototype['has_more'] = undefined;






export default AffiliateReferralReport;

