/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The AllPositions model module.
 * @module model/AllPositions
 * @version 1.0.0
 */
export default class AllPositions {
  /**
   * Constructs a new <code>AllPositions</code>.
   * @alias module:model/AllPositions
   * @class
   * @param allPositions {Object} 
   */
  constructor(allPositions) {
    this.allPositions = allPositions;
  }

  /**
   * Constructs a <code>AllPositions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllPositions} obj Optional instance to populate.
   * @return {module:model/AllPositions} The populated <code>AllPositions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AllPositions();
      if (data.hasOwnProperty('all_positions'))
        obj.allPositions = ApiClient.convertToType(data['all_positions'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} allPositions
 */
AllPositions.prototype.allPositions = undefined;

