/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AssetKind from './AssetKind';
import Bond from './Bond';

/**
 * The Asset model module.
 * @module model/Asset
 * @version 1.0.0
 */
export default class Asset {
  /**
   * Constructs a new <code>Asset</code>.
   * @alias module:model/Asset
   * @class
   * @param id {Object} 
   * @param collateralWeight {Object} 
   * @param createdAt {Object} 
   * @param decimals {Object} 
   * @param fractionalizedUnits {Object} 
   * @param description {Object} 
   * @param liquidationWeight {Object} 
   * @param maxSupply {Object} 
   * @param maxUtilization {Object} 
   * @param name {Object} 
   * @param symbol {Object} 
   * @param kind {module:model/AssetKind} 
   * @param _yield {Object} 
   * @param canAddLiquidity {Object} 
   * @param canDirectBorrow {Object} 
   * @param canOnboard {Object} 
   * @param canTrade {Object} 
   * @param canVirtualBorrow {Object} 
   * @param maxLeverage {Object} 
   * @param leverageInterestRate {Object} 
   */
  constructor(id, collateralWeight, createdAt, decimals, fractionalizedUnits, description, liquidationWeight, maxSupply, maxUtilization, name, symbol, kind, _yield, canAddLiquidity, canDirectBorrow, canOnboard, canTrade, canVirtualBorrow, maxLeverage, leverageInterestRate) {
    this.id = id;
    this.collateralWeight = collateralWeight;
    this.createdAt = createdAt;
    this.decimals = decimals;
    this.fractionalizedUnits = fractionalizedUnits;
    this.description = description;
    this.liquidationWeight = liquidationWeight;
    this.maxSupply = maxSupply;
    this.maxUtilization = maxUtilization;
    this.name = name;
    this.symbol = symbol;
    this.kind = kind;
    this._yield = _yield;
    this.canAddLiquidity = canAddLiquidity;
    this.canDirectBorrow = canDirectBorrow;
    this.canOnboard = canOnboard;
    this.canTrade = canTrade;
    this.canVirtualBorrow = canVirtualBorrow;
    this.maxLeverage = maxLeverage;
    this.leverageInterestRate = leverageInterestRate;
  }

  /**
   * Constructs a <code>Asset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Asset} obj Optional instance to populate.
   * @return {module:model/Asset} The populated <code>Asset</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Asset();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], Object);
      if (data.hasOwnProperty('collateral_weight'))
        obj.collateralWeight = ApiClient.convertToType(data['collateral_weight'], Object);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], Object);
      if (data.hasOwnProperty('decimals'))
        obj.decimals = ApiClient.convertToType(data['decimals'], Object);
      if (data.hasOwnProperty('fractionalized_units'))
        obj.fractionalizedUnits = ApiClient.convertToType(data['fractionalized_units'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], Object);
      if (data.hasOwnProperty('liquidation_weight'))
        obj.liquidationWeight = ApiClient.convertToType(data['liquidation_weight'], Object);
      if (data.hasOwnProperty('max_supply'))
        obj.maxSupply = ApiClient.convertToType(data['max_supply'], Object);
      if (data.hasOwnProperty('max_utilization'))
        obj.maxUtilization = ApiClient.convertToType(data['max_utilization'], Object);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], Object);
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], Object);
      if (data.hasOwnProperty('kind'))
        obj.kind = AssetKind.constructFromObject(data['kind']);
      if (data.hasOwnProperty('yield'))
        obj._yield = ApiClient.convertToType(data['yield'], Object);
      if (data.hasOwnProperty('can_add_liquidity'))
        obj.canAddLiquidity = ApiClient.convertToType(data['can_add_liquidity'], Object);
      if (data.hasOwnProperty('can_direct_borrow'))
        obj.canDirectBorrow = ApiClient.convertToType(data['can_direct_borrow'], Object);
      if (data.hasOwnProperty('can_onboard'))
        obj.canOnboard = ApiClient.convertToType(data['can_onboard'], Object);
      if (data.hasOwnProperty('can_trade'))
        obj.canTrade = ApiClient.convertToType(data['can_trade'], Object);
      if (data.hasOwnProperty('can_virtual_borrow'))
        obj.canVirtualBorrow = ApiClient.convertToType(data['can_virtual_borrow'], Object);
      if (data.hasOwnProperty('max_leverage'))
        obj.maxLeverage = ApiClient.convertToType(data['max_leverage'], Object);
      if (data.hasOwnProperty('leverage_interest_rate'))
        obj.leverageInterestRate = ApiClient.convertToType(data['leverage_interest_rate'], Object);
      if (data.hasOwnProperty('bond'))
        obj.bond = Bond.constructFromObject(data['bond']);
    }
    return obj;
  }
}

/**
 * @member {Object} id
 */
Asset.prototype.id = undefined;

/**
 * @member {Object} collateralWeight
 */
Asset.prototype.collateralWeight = undefined;

/**
 * @member {Object} createdAt
 */
Asset.prototype.createdAt = undefined;

/**
 * @member {Object} decimals
 */
Asset.prototype.decimals = undefined;

/**
 * @member {Object} fractionalizedUnits
 */
Asset.prototype.fractionalizedUnits = undefined;

/**
 * @member {Object} description
 */
Asset.prototype.description = undefined;

/**
 * @member {Object} liquidationWeight
 */
Asset.prototype.liquidationWeight = undefined;

/**
 * @member {Object} maxSupply
 */
Asset.prototype.maxSupply = undefined;

/**
 * @member {Object} maxUtilization
 */
Asset.prototype.maxUtilization = undefined;

/**
 * @member {Object} name
 */
Asset.prototype.name = undefined;

/**
 * @member {Object} symbol
 */
Asset.prototype.symbol = undefined;

/**
 * @member {module:model/AssetKind} kind
 */
Asset.prototype.kind = undefined;

/**
 * @member {Object} _yield
 */
Asset.prototype._yield = undefined;

/**
 * @member {Object} canAddLiquidity
 */
Asset.prototype.canAddLiquidity = undefined;

/**
 * @member {Object} canDirectBorrow
 */
Asset.prototype.canDirectBorrow = undefined;

/**
 * @member {Object} canOnboard
 */
Asset.prototype.canOnboard = undefined;

/**
 * @member {Object} canTrade
 */
Asset.prototype.canTrade = undefined;

/**
 * @member {Object} canVirtualBorrow
 */
Asset.prototype.canVirtualBorrow = undefined;

/**
 * @member {Object} maxLeverage
 */
Asset.prototype.maxLeverage = undefined;

/**
 * @member {Object} leverageInterestRate
 */
Asset.prototype.leverageInterestRate = undefined;

/**
 * @member {module:model/Bond} bond
 */
Asset.prototype.bond = undefined;

