/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetYield model module.
 * @module model/AssetYield
 * @version 1.0.0
 */
class AssetYield {
    /**
     * Constructs a new <code>AssetYield</code>.
     * @alias module:model/AssetYield
     * @param assetId {String} 
     * @param timestamp {Date} 
     * @param ytm {String} 
     * @param borrowingYieldRate {String} 
     * @param lendingYieldRate {String} 
     * @param price {String} 
     * @param tvl {String} 
     * @param totalYield {String} 
     */
    constructor(assetId, timestamp, ytm, borrowingYieldRate, lendingYieldRate, price, tvl, totalYield) { 
        
        AssetYield.initialize(this, assetId, timestamp, ytm, borrowingYieldRate, lendingYieldRate, price, tvl, totalYield);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetId, timestamp, ytm, borrowingYieldRate, lendingYieldRate, price, tvl, totalYield) { 
        obj['asset_id'] = assetId;
        obj['timestamp'] = timestamp;
        obj['ytm'] = ytm;
        obj['borrowing_yield_rate'] = borrowingYieldRate;
        obj['lending_yield_rate'] = lendingYieldRate;
        obj['price'] = price;
        obj['tvl'] = tvl;
        obj['total_yield'] = totalYield;
    }

    /**
     * Constructs a <code>AssetYield</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetYield} obj Optional instance to populate.
     * @return {module:model/AssetYield} The populated <code>AssetYield</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetYield();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('ytm')) {
                obj['ytm'] = ApiClient.convertToType(data['ytm'], 'String');
            }
            if (data.hasOwnProperty('borrowing_yield_rate')) {
                obj['borrowing_yield_rate'] = ApiClient.convertToType(data['borrowing_yield_rate'], 'String');
            }
            if (data.hasOwnProperty('lending_yield_rate')) {
                obj['lending_yield_rate'] = ApiClient.convertToType(data['lending_yield_rate'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'String');
            }
            if (data.hasOwnProperty('tvl')) {
                obj['tvl'] = ApiClient.convertToType(data['tvl'], 'String');
            }
            if (data.hasOwnProperty('total_yield')) {
                obj['total_yield'] = ApiClient.convertToType(data['total_yield'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetYield</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetYield</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AssetYield.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is a string
        if (data['ytm'] && !(typeof data['ytm'] === 'string' || data['ytm'] instanceof String)) {
            throw new Error("Expected the field `ytm` to be a primitive type in the JSON string but got " + data['ytm']);
        }
        // ensure the json data is a string
        if (data['borrowing_yield_rate'] && !(typeof data['borrowing_yield_rate'] === 'string' || data['borrowing_yield_rate'] instanceof String)) {
            throw new Error("Expected the field `borrowing_yield_rate` to be a primitive type in the JSON string but got " + data['borrowing_yield_rate']);
        }
        // ensure the json data is a string
        if (data['lending_yield_rate'] && !(typeof data['lending_yield_rate'] === 'string' || data['lending_yield_rate'] instanceof String)) {
            throw new Error("Expected the field `lending_yield_rate` to be a primitive type in the JSON string but got " + data['lending_yield_rate']);
        }
        // ensure the json data is a string
        if (data['price'] && !(typeof data['price'] === 'string' || data['price'] instanceof String)) {
            throw new Error("Expected the field `price` to be a primitive type in the JSON string but got " + data['price']);
        }
        // ensure the json data is a string
        if (data['tvl'] && !(typeof data['tvl'] === 'string' || data['tvl'] instanceof String)) {
            throw new Error("Expected the field `tvl` to be a primitive type in the JSON string but got " + data['tvl']);
        }
        // ensure the json data is a string
        if (data['total_yield'] && !(typeof data['total_yield'] === 'string' || data['total_yield'] instanceof String)) {
            throw new Error("Expected the field `total_yield` to be a primitive type in the JSON string but got " + data['total_yield']);
        }

        return true;
    }


}

AssetYield.RequiredProperties = ["asset_id", "timestamp", "ytm", "borrowing_yield_rate", "lending_yield_rate", "price", "tvl", "total_yield"];

/**
 * @member {String} asset_id
 */
AssetYield.prototype['asset_id'] = undefined;

/**
 * @member {Date} timestamp
 */
AssetYield.prototype['timestamp'] = undefined;

/**
 * @member {String} ytm
 */
AssetYield.prototype['ytm'] = undefined;

/**
 * @member {String} borrowing_yield_rate
 */
AssetYield.prototype['borrowing_yield_rate'] = undefined;

/**
 * @member {String} lending_yield_rate
 */
AssetYield.prototype['lending_yield_rate'] = undefined;

/**
 * @member {String} price
 */
AssetYield.prototype['price'] = undefined;

/**
 * @member {String} tvl
 */
AssetYield.prototype['tvl'] = undefined;

/**
 * @member {String} total_yield
 */
AssetYield.prototype['total_yield'] = undefined;






export default AssetYield;

