/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The BalanceTransfer model module.
 * @module model/BalanceTransfer
 * @version 1.0.0
 */
export default class BalanceTransfer {
  /**
   * Constructs a new <code>BalanceTransfer</code>.
   * @alias module:model/BalanceTransfer
   * @class
   * @param fromPositionId {Object} 
   * @param toPositionId {Object} 
   * @param transactionId {Object} 
   */
  constructor(fromPositionId, toPositionId, transactionId) {
    this.fromPositionId = fromPositionId;
    this.toPositionId = toPositionId;
    this.transactionId = transactionId;
  }

  /**
   * Constructs a <code>BalanceTransfer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BalanceTransfer} obj Optional instance to populate.
   * @return {module:model/BalanceTransfer} The populated <code>BalanceTransfer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BalanceTransfer();
      if (data.hasOwnProperty('from_position_id'))
        obj.fromPositionId = ApiClient.convertToType(data['from_position_id'], Object);
      if (data.hasOwnProperty('to_position_id'))
        obj.toPositionId = ApiClient.convertToType(data['to_position_id'], Object);
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} fromPositionId
 */
BalanceTransfer.prototype.fromPositionId = undefined;

/**
 * @member {Object} toPositionId
 */
BalanceTransfer.prototype.toPositionId = undefined;

/**
 * @member {Object} transactionId
 */
BalanceTransfer.prototype.transactionId = undefined;

