/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class BondKind.
 * @enum {Object}
 * @readonly
 */
const BondKind = {
  /**
   * value: "COUPON-PAYING"
   * @const
   */
  COUPON_PAYING: "COUPON-PAYING",

  /**
   * value: "PRINCIPAL-ONLY"
   * @const
   */
  PRINCIPAL_ONLY: "PRINCIPAL-ONLY",

  /**
   * Returns a <code>BondKind</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/BondKind} The enum <code>BondKind</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {BondKind};