/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CancelOrdersResponseData model module.
 * @module model/CancelOrdersResponseData
 * @version 1.0.0
 */
export default class CancelOrdersResponseData {
  /**
   * Constructs a new <code>CancelOrdersResponseData</code>.
   * @alias module:model/CancelOrdersResponseData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CancelOrdersResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CancelOrdersResponseData} obj Optional instance to populate.
   * @return {module:model/CancelOrdersResponseData} The populated <code>CancelOrdersResponseData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CancelOrdersResponseData();
      if (data.hasOwnProperty('cancelled_order_ids'))
        obj.cancelledOrderIds = ApiClient.convertToType(data['cancelled_order_ids'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} cancelledOrderIds
 */
CancelOrdersResponseData.prototype.cancelledOrderIds = undefined;

