/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import Order from './Order';
import ResponseEnvelope from './ResponseEnvelope';

/**
 * The CancelOrderResponseEnvelope model module.
 * @module model/CancelOrderResponseEnvelope
 * @version 1.0.0
 */
export default class CancelOrderResponseEnvelope extends ResponseEnvelope {
  /**
   * Constructs a new <code>CancelOrderResponseEnvelope</code>.
   * @alias module:model/CancelOrderResponseEnvelope
   * @class
   * @extends module:model/ResponseEnvelope
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>CancelOrderResponseEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CancelOrderResponseEnvelope} obj Optional instance to populate.
   * @return {module:model/CancelOrderResponseEnvelope} The populated <code>CancelOrderResponseEnvelope</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CancelOrderResponseEnvelope();
      ResponseEnvelope.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = Order.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Order} data
 */
CancelOrderResponseEnvelope.prototype.data = undefined;

