/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ClosePositionRequest model module.
 * @module model/ClosePositionRequest
 * @version 1.0.0
 */
export default class ClosePositionRequest {
  /**
   * Constructs a new <code>ClosePositionRequest</code>.
   * @alias module:model/ClosePositionRequest
   * @class
   * @param positionId {Object} 
   * @param orderBookId {Object} 
   */
  constructor(positionId, orderBookId) {
    this.positionId = positionId;
    this.orderBookId = orderBookId;
  }

  /**
   * Constructs a <code>ClosePositionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClosePositionRequest} obj Optional instance to populate.
   * @return {module:model/ClosePositionRequest} The populated <code>ClosePositionRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClosePositionRequest();
      if (data.hasOwnProperty('position_id'))
        obj.positionId = ApiClient.convertToType(data['position_id'], Object);
      if (data.hasOwnProperty('order_book_id'))
        obj.orderBookId = ApiClient.convertToType(data['order_book_id'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} positionId
 */
ClosePositionRequest.prototype.positionId = undefined;

/**
 * @member {Object} orderBookId
 */
ClosePositionRequest.prototype.orderBookId = undefined;

