/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ClosePositionResp model module.
 * @module model/ClosePositionResp
 * @version 1.0.0
 */
export default class ClosePositionResp {
  /**
   * Constructs a new <code>ClosePositionResp</code>.
   * @alias module:model/ClosePositionResp
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClosePositionResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClosePositionResp} obj Optional instance to populate.
   * @return {module:model/ClosePositionResp} The populated <code>ClosePositionResp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClosePositionResp();
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} orderId
 */
ClosePositionResp.prototype.orderId = undefined;

