/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CouponPayment model module.
 * @module model/CouponPayment
 * @version 1.0.0
 */
class CouponPayment {
    /**
     * Constructs a new <code>CouponPayment</code>.
     * @alias module:model/CouponPayment
     * @param id {String} 
     * @param assetId {String} 
     * @param _yield {Number} 
     * @param startAt {Date} 
     * @param endAt {Date} 
     * @param payAt {Date} 
     * @param availableToPay {String} 
     * @param completedAt {Date} 
     * @param createdAt {Date} 
     * @param processEvery {Number} Number of nanoseconds to wait between coupon payment processing, must be at least 1000 (1 microsecond)
     * @param lastProcessedAt {Date} 
     */
    constructor(id, assetId, _yield, startAt, endAt, payAt, availableToPay, completedAt, createdAt, processEvery, lastProcessedAt) { 
        
        CouponPayment.initialize(this, id, assetId, _yield, startAt, endAt, payAt, availableToPay, completedAt, createdAt, processEvery, lastProcessedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, assetId, _yield, startAt, endAt, payAt, availableToPay, completedAt, createdAt, processEvery, lastProcessedAt) { 
        obj['id'] = id;
        obj['asset_id'] = assetId;
        obj['yield'] = _yield;
        obj['start_at'] = startAt;
        obj['end_at'] = endAt;
        obj['pay_at'] = payAt;
        obj['available_to_pay'] = availableToPay;
        obj['completed_at'] = completedAt;
        obj['created_at'] = createdAt;
        obj['process_every'] = processEvery;
        obj['last_processed_at'] = lastProcessedAt;
    }

    /**
     * Constructs a <code>CouponPayment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CouponPayment} obj Optional instance to populate.
     * @return {module:model/CouponPayment} The populated <code>CouponPayment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CouponPayment();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('yield')) {
                obj['yield'] = ApiClient.convertToType(data['yield'], 'Number');
            }
            if (data.hasOwnProperty('start_at')) {
                obj['start_at'] = ApiClient.convertToType(data['start_at'], 'Date');
            }
            if (data.hasOwnProperty('end_at')) {
                obj['end_at'] = ApiClient.convertToType(data['end_at'], 'Date');
            }
            if (data.hasOwnProperty('pay_at')) {
                obj['pay_at'] = ApiClient.convertToType(data['pay_at'], 'Date');
            }
            if (data.hasOwnProperty('available_to_pay')) {
                obj['available_to_pay'] = ApiClient.convertToType(data['available_to_pay'], 'String');
            }
            if (data.hasOwnProperty('completed_at')) {
                obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'Date');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('process_every')) {
                obj['process_every'] = ApiClient.convertToType(data['process_every'], 'Number');
            }
            if (data.hasOwnProperty('last_processed_at')) {
                obj['last_processed_at'] = ApiClient.convertToType(data['last_processed_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CouponPayment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CouponPayment</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CouponPayment.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is a string
        if (data['available_to_pay'] && !(typeof data['available_to_pay'] === 'string' || data['available_to_pay'] instanceof String)) {
            throw new Error("Expected the field `available_to_pay` to be a primitive type in the JSON string but got " + data['available_to_pay']);
        }

        return true;
    }


}

CouponPayment.RequiredProperties = ["id", "asset_id", "yield", "start_at", "end_at", "pay_at", "available_to_pay", "completed_at", "created_at", "process_every", "last_processed_at"];

/**
 * @member {String} id
 */
CouponPayment.prototype['id'] = undefined;

/**
 * @member {String} asset_id
 */
CouponPayment.prototype['asset_id'] = undefined;

/**
 * @member {Number} yield
 */
CouponPayment.prototype['yield'] = undefined;

/**
 * @member {Date} start_at
 */
CouponPayment.prototype['start_at'] = undefined;

/**
 * @member {Date} end_at
 */
CouponPayment.prototype['end_at'] = undefined;

/**
 * @member {Date} pay_at
 */
CouponPayment.prototype['pay_at'] = undefined;

/**
 * @member {String} available_to_pay
 */
CouponPayment.prototype['available_to_pay'] = undefined;

/**
 * @member {Date} completed_at
 */
CouponPayment.prototype['completed_at'] = undefined;

/**
 * @member {Date} created_at
 */
CouponPayment.prototype['created_at'] = undefined;

/**
 * Number of nanoseconds to wait between coupon payment processing, must be at least 1000 (1 microsecond)
 * @member {Number} process_every
 */
CouponPayment.prototype['process_every'] = undefined;

/**
 * @member {Date} last_processed_at
 */
CouponPayment.prototype['last_processed_at'] = undefined;






export default CouponPayment;

