/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CountryCode from './CountryCode';

/**
 * The CreateIntegratorUserRequest model module.
 * @module model/CreateIntegratorUserRequest
 * @version 1.0.0
 */
class CreateIntegratorUserRequest {
    /**
     * Constructs a new <code>CreateIntegratorUserRequest</code>.
     * @alias module:model/CreateIntegratorUserRequest
     */
    constructor() { 
        
        CreateIntegratorUserRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateIntegratorUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateIntegratorUserRequest} obj Optional instance to populate.
     * @return {module:model/CreateIntegratorUserRequest} The populated <code>CreateIntegratorUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateIntegratorUserRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('country_of_domicile')) {
                obj['country_of_domicile'] = CountryCode.constructFromObject(data['country_of_domicile']);
            }
            if (data.hasOwnProperty('native_asset_id')) {
                obj['native_asset_id'] = ApiClient.convertToType(data['native_asset_id'], 'String');
            }
            if (data.hasOwnProperty('photo_url')) {
                obj['photo_url'] = ApiClient.convertToType(data['photo_url'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('provider_id')) {
                obj['provider_id'] = ApiClient.convertToType(data['provider_id'], 'String');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateIntegratorUserRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateIntegratorUserRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['first_name'] && !(typeof data['first_name'] === 'string' || data['first_name'] instanceof String)) {
            throw new Error("Expected the field `first_name` to be a primitive type in the JSON string but got " + data['first_name']);
        }
        // ensure the json data is a string
        if (data['last_name'] && !(typeof data['last_name'] === 'string' || data['last_name'] instanceof String)) {
            throw new Error("Expected the field `last_name` to be a primitive type in the JSON string but got " + data['last_name']);
        }
        // ensure the json data is a string
        if (data['native_asset_id'] && !(typeof data['native_asset_id'] === 'string' || data['native_asset_id'] instanceof String)) {
            throw new Error("Expected the field `native_asset_id` to be a primitive type in the JSON string but got " + data['native_asset_id']);
        }
        // ensure the json data is a string
        if (data['photo_url'] && !(typeof data['photo_url'] === 'string' || data['photo_url'] instanceof String)) {
            throw new Error("Expected the field `photo_url` to be a primitive type in the JSON string but got " + data['photo_url']);
        }
        // ensure the json data is a string
        if (data['provider'] && !(typeof data['provider'] === 'string' || data['provider'] instanceof String)) {
            throw new Error("Expected the field `provider` to be a primitive type in the JSON string but got " + data['provider']);
        }
        // ensure the json data is a string
        if (data['provider_id'] && !(typeof data['provider_id'] === 'string' || data['provider_id'] instanceof String)) {
            throw new Error("Expected the field `provider_id` to be a primitive type in the JSON string but got " + data['provider_id']);
        }
        // ensure the json data is a string
        if (data['timezone'] && !(typeof data['timezone'] === 'string' || data['timezone'] instanceof String)) {
            throw new Error("Expected the field `timezone` to be a primitive type in the JSON string but got " + data['timezone']);
        }

        return true;
    }


}



/**
 * @member {String} email
 */
CreateIntegratorUserRequest.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
CreateIntegratorUserRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
CreateIntegratorUserRequest.prototype['last_name'] = undefined;

/**
 * @member {module:model/CountryCode} country_of_domicile
 */
CreateIntegratorUserRequest.prototype['country_of_domicile'] = undefined;

/**
 * @member {String} native_asset_id
 */
CreateIntegratorUserRequest.prototype['native_asset_id'] = undefined;

/**
 * @member {String} photo_url
 */
CreateIntegratorUserRequest.prototype['photo_url'] = undefined;

/**
 * @member {String} provider
 */
CreateIntegratorUserRequest.prototype['provider'] = undefined;

/**
 * @member {String} provider_id
 */
CreateIntegratorUserRequest.prototype['provider_id'] = undefined;

/**
 * @member {String} timezone
 */
CreateIntegratorUserRequest.prototype['timezone'] = undefined;






export default CreateIntegratorUserRequest;

