/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateAPIKeyResponse model module.
 * @module model/CreateAPIKeyResponse
 * @version 1.0.0
 */
export default class CreateAPIKeyResponse {
  /**
   * Constructs a new <code>CreateAPIKeyResponse</code>.
   * @alias module:model/CreateAPIKeyResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateAPIKeyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAPIKeyResponse} obj Optional instance to populate.
   * @return {module:model/CreateAPIKeyResponse} The populated <code>CreateAPIKeyResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateAPIKeyResponse();
      if (data.hasOwnProperty('key_id'))
        obj.keyId = ApiClient.convertToType(data['key_id'], 'String');
      if (data.hasOwnProperty('api_key'))
        obj.apiKey = ApiClient.convertToType(data['api_key'], 'String');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} keyId
 */
CreateAPIKeyResponse.prototype.keyId = undefined;

/**
 * @member {String} apiKey
 */
CreateAPIKeyResponse.prototype.apiKey = undefined;

/**
 * @member {String} label
 */
CreateAPIKeyResponse.prototype.label = undefined;

