/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import OrderKind from './OrderKind';
import OrderModifierKind from './OrderModifierKind';
import Side from './Side';

/**
 * The CreateOrderRequest model module.
 * @module model/CreateOrderRequest
 * @version 1.0.0
 */
export default class CreateOrderRequest {
  /**
   * Constructs a new <code>CreateOrderRequest</code>.
   * @alias module:model/CreateOrderRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateOrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateOrderRequest} obj Optional instance to populate.
   * @return {module:model/CreateOrderRequest} The populated <code>CreateOrderRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateOrderRequest();
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'String');
      if (data.hasOwnProperty('inverse_leverage'))
        obj.inverseLeverage = ApiClient.convertToType(data['inverse_leverage'], 'Number');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'String');
      if (data.hasOwnProperty('kind'))
        obj.kind = OrderKind.constructFromObject(data['kind']);
      if (data.hasOwnProperty('side'))
        obj.side = Side.constructFromObject(data['side']);
      if (data.hasOwnProperty('order_book_id'))
        obj.orderBookId = ApiClient.convertToType(data['order_book_id'], 'String');
      if (data.hasOwnProperty('user_text'))
        obj.userText = ApiClient.convertToType(data['user_text'], 'String');
      if (data.hasOwnProperty('order_modifiers'))
        obj.orderModifiers = ApiClient.convertToType(data['order_modifiers'], [OrderModifierKind]);
    }
    return obj;
  }
}

/**
 * @member {String} quantity
 */
CreateOrderRequest.prototype.quantity = undefined;

/**
 * Required: Inverse leverage for the order, must be between 0 and 1 (inclusive)
 * @member {Number} inverseLeverage
 */
CreateOrderRequest.prototype.inverseLeverage = undefined;

/**
 * @member {String} price
 */
CreateOrderRequest.prototype.price = undefined;

/**
 * @member {module:model/OrderKind} kind
 */
CreateOrderRequest.prototype.kind = undefined;

/**
 * @member {module:model/Side} side
 */
CreateOrderRequest.prototype.side = undefined;

/**
 * Required: the order book to submit the order to
 * @member {String} orderBookId
 */
CreateOrderRequest.prototype.orderBookId = undefined;

/**
 * Optional: User-defined text for the order, e.g., 'buying dips'
 * @member {String} userText
 */
CreateOrderRequest.prototype.userText = undefined;

/**
 * @member {Array.<module:model/OrderModifierKind>} orderModifiers
 */
CreateOrderRequest.prototype.orderModifiers = undefined;

