/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateConditionalOrderResponseData model module.
 * @module model/CreateConditionalOrderResponseData
 * @version 1.0.0
 */
class CreateConditionalOrderResponseData {
    /**
     * Constructs a new <code>CreateConditionalOrderResponseData</code>.
     * @alias module:model/CreateConditionalOrderResponseData
     */
    constructor() { 
        
        CreateConditionalOrderResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateConditionalOrderResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateConditionalOrderResponseData} obj Optional instance to populate.
     * @return {module:model/CreateConditionalOrderResponseData} The populated <code>CreateConditionalOrderResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateConditionalOrderResponseData();

            if (data.hasOwnProperty('stop_loss_order_id')) {
                obj['stop_loss_order_id'] = ApiClient.convertToType(data['stop_loss_order_id'], 'String');
            }
            if (data.hasOwnProperty('take_profit_order_id')) {
                obj['take_profit_order_id'] = ApiClient.convertToType(data['take_profit_order_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateConditionalOrderResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateConditionalOrderResponseData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['stop_loss_order_id'] && !(typeof data['stop_loss_order_id'] === 'string' || data['stop_loss_order_id'] instanceof String)) {
            throw new Error("Expected the field `stop_loss_order_id` to be a primitive type in the JSON string but got " + data['stop_loss_order_id']);
        }
        // ensure the json data is a string
        if (data['take_profit_order_id'] && !(typeof data['take_profit_order_id'] === 'string' || data['take_profit_order_id'] instanceof String)) {
            throw new Error("Expected the field `take_profit_order_id` to be a primitive type in the JSON string but got " + data['take_profit_order_id']);
        }

        return true;
    }


}



/**
 * @member {String} stop_loss_order_id
 */
CreateConditionalOrderResponseData.prototype['stop_loss_order_id'] = undefined;

/**
 * @member {String} take_profit_order_id
 */
CreateConditionalOrderResponseData.prototype['take_profit_order_id'] = undefined;






export default CreateConditionalOrderResponseData;

