/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeCollateralizeResponse model module.
 * @module model/DeCollateralizeResponse
 * @version 1.0.0
 */
export default class DeCollateralizeResponse {
  /**
   * Constructs a new <code>DeCollateralizeResponse</code>.
   * @alias module:model/DeCollateralizeResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeCollateralizeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeCollateralizeResponse} obj Optional instance to populate.
   * @return {module:model/DeCollateralizeResponse} The populated <code>DeCollateralizeResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeCollateralizeResponse();
      if (data.hasOwnProperty('position_id'))
        obj.positionId = ApiClient.convertToType(data['position_id'], 'String');
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], 'String');
      if (data.hasOwnProperty('asset_id'))
        obj.assetId = ApiClient.convertToType(data['asset_id'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} positionId
 */
DeCollateralizeResponse.prototype.positionId = undefined;

/**
 * @member {String} transactionId
 */
DeCollateralizeResponse.prototype.transactionId = undefined;

/**
 * @member {String} assetId
 */
DeCollateralizeResponse.prototype.assetId = undefined;

/**
 * @member {String} quantity
 */
DeCollateralizeResponse.prototype.quantity = undefined;

