/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DepositArgs model module.
 * @module model/DepositArgs
 * @version 1.0.0
 */
class DepositArgs {
    /**
     * Constructs a new <code>DepositArgs</code>.
     * The non-signature arguments to the vault deposit() call. The remaining (v, r, s) arguments come from the permit signature the client obtains by signing the approval.
     * @alias module:model/DepositArgs
     * @param quantity {String} Deposit quantity in USDC base units (10^-6 USDC), as a decimal string. Matches the permit's value.
     * @param userId {String} The caller's user ID as 16 bytes, 0x-prefixed hex. Stored on-chain with the deposit and mapped back to the user by the indexer.
     * @param clientReferenceId {String} The bytes32 client reference as a 0x-prefixed hex string. All zero bytes when not supplied.
     * @param deadline {String} Unix timestamp (seconds), as a decimal string. Matches the permit's deadline exactly.
     */
    constructor(quantity, userId, clientReferenceId, deadline) { 
        
        DepositArgs.initialize(this, quantity, userId, clientReferenceId, deadline);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quantity, userId, clientReferenceId, deadline) { 
        obj['quantity'] = quantity;
        obj['user_id'] = userId;
        obj['client_reference_id'] = clientReferenceId;
        obj['deadline'] = deadline;
    }

    /**
     * Constructs a <code>DepositArgs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DepositArgs} obj Optional instance to populate.
     * @return {module:model/DepositArgs} The populated <code>DepositArgs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DepositArgs();

            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('client_reference_id')) {
                obj['client_reference_id'] = ApiClient.convertToType(data['client_reference_id'], 'String');
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DepositArgs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DepositArgs</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DepositArgs.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['quantity'] && !(typeof data['quantity'] === 'string' || data['quantity'] instanceof String)) {
            throw new Error("Expected the field `quantity` to be a primitive type in the JSON string but got " + data['quantity']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['client_reference_id'] && !(typeof data['client_reference_id'] === 'string' || data['client_reference_id'] instanceof String)) {
            throw new Error("Expected the field `client_reference_id` to be a primitive type in the JSON string but got " + data['client_reference_id']);
        }
        // ensure the json data is a string
        if (data['deadline'] && !(typeof data['deadline'] === 'string' || data['deadline'] instanceof String)) {
            throw new Error("Expected the field `deadline` to be a primitive type in the JSON string but got " + data['deadline']);
        }

        return true;
    }


}

DepositArgs.RequiredProperties = ["quantity", "user_id", "client_reference_id", "deadline"];

/**
 * Deposit quantity in USDC base units (10^-6 USDC), as a decimal string. Matches the permit's value.
 * @member {String} quantity
 */
DepositArgs.prototype['quantity'] = undefined;

/**
 * The caller's user ID as 16 bytes, 0x-prefixed hex. Stored on-chain with the deposit and mapped back to the user by the indexer.
 * @member {String} user_id
 */
DepositArgs.prototype['user_id'] = undefined;

/**
 * The bytes32 client reference as a 0x-prefixed hex string. All zero bytes when not supplied.
 * @member {String} client_reference_id
 */
DepositArgs.prototype['client_reference_id'] = undefined;

/**
 * Unix timestamp (seconds), as a decimal string. Matches the permit's deadline exactly.
 * @member {String} deadline
 */
DepositArgs.prototype['deadline'] = undefined;






export default DepositArgs;

