/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FundUserRequest model module.
 * @module model/FundUserRequest
 * @version 1.0.0
 */
export default class FundUserRequest {
  /**
   * Constructs a new <code>FundUserRequest</code>.
   * @alias module:model/FundUserRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FundUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FundUserRequest} obj Optional instance to populate.
   * @return {module:model/FundUserRequest} The populated <code>FundUserRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FundUserRequest();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('asset_id'))
        obj.assetId = ApiClient.convertToType(data['asset_id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
FundUserRequest.prototype.userId = undefined;

/**
 * @member {String} assetId
 */
FundUserRequest.prototype.assetId = undefined;

/**
 * @member {String} amount
 */
FundUserRequest.prototype.amount = undefined;

