/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FundUser model module.
 * @module model/FundUser
 * @version 1.0.0
 */
class FundUser {
    /**
     * Constructs a new <code>FundUser</code>.
     * @alias module:model/FundUser
     * @param userId {String} 
     * @param positionId {String} 
     * @param assetId {String} 
     * @param finalQuantity {String} 
     * @param amount {String} 
     */
    constructor(userId, positionId, assetId, finalQuantity, amount) { 
        
        FundUser.initialize(this, userId, positionId, assetId, finalQuantity, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId, positionId, assetId, finalQuantity, amount) { 
        obj['user_id'] = userId;
        obj['position_id'] = positionId;
        obj['asset_id'] = assetId;
        obj['final_quantity'] = finalQuantity;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>FundUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FundUser} obj Optional instance to populate.
     * @return {module:model/FundUser} The populated <code>FundUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FundUser();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('position_id')) {
                obj['position_id'] = ApiClient.convertToType(data['position_id'], 'String');
            }
            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('final_quantity')) {
                obj['final_quantity'] = ApiClient.convertToType(data['final_quantity'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FundUser</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FundUser</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FundUser.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['position_id'] && !(typeof data['position_id'] === 'string' || data['position_id'] instanceof String)) {
            throw new Error("Expected the field `position_id` to be a primitive type in the JSON string but got " + data['position_id']);
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is a string
        if (data['final_quantity'] && !(typeof data['final_quantity'] === 'string' || data['final_quantity'] instanceof String)) {
            throw new Error("Expected the field `final_quantity` to be a primitive type in the JSON string but got " + data['final_quantity']);
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }

        return true;
    }


}

FundUser.RequiredProperties = ["user_id", "position_id", "asset_id", "final_quantity", "amount"];

/**
 * @member {String} user_id
 */
FundUser.prototype['user_id'] = undefined;

/**
 * @member {String} position_id
 */
FundUser.prototype['position_id'] = undefined;

/**
 * @member {String} asset_id
 */
FundUser.prototype['asset_id'] = undefined;

/**
 * @member {String} final_quantity
 */
FundUser.prototype['final_quantity'] = undefined;

/**
 * @member {String} amount
 */
FundUser.prototype['amount'] = undefined;






export default FundUser;

