/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IsolateCollateralResponse model module.
 * @module model/IsolateCollateralResponse
 * @version 1.0.0
 */
export default class IsolateCollateralResponse {
  /**
   * Constructs a new <code>IsolateCollateralResponse</code>.
   * @alias module:model/IsolateCollateralResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IsolateCollateralResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IsolateCollateralResponse} obj Optional instance to populate.
   * @return {module:model/IsolateCollateralResponse} The populated <code>IsolateCollateralResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IsolateCollateralResponse();
      if (data.hasOwnProperty('global_position_id'))
        obj.globalPositionId = ApiClient.convertToType(data['global_position_id'], 'String');
      if (data.hasOwnProperty('isolated_position_id'))
        obj.isolatedPositionId = ApiClient.convertToType(data['isolated_position_id'], 'String');
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], 'String');
      if (data.hasOwnProperty('asset_id'))
        obj.assetId = ApiClient.convertToType(data['asset_id'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} globalPositionId
 */
IsolateCollateralResponse.prototype.globalPositionId = undefined;

/**
 * @member {String} isolatedPositionId
 */
IsolateCollateralResponse.prototype.isolatedPositionId = undefined;

/**
 * @member {String} transactionId
 */
IsolateCollateralResponse.prototype.transactionId = undefined;

/**
 * @member {String} assetId
 */
IsolateCollateralResponse.prototype.assetId = undefined;

/**
 * @member {String} quantity
 */
IsolateCollateralResponse.prototype.quantity = undefined;

