/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IssuedPromoLink model module.
 * @module model/IssuedPromoLink
 * @version 1.0.0
 */
class IssuedPromoLink {
    /**
     * Constructs a new <code>IssuedPromoLink</code>.
     * @alias module:model/IssuedPromoLink
     * @param id {String} 
     * @param tokenPrefix {String} 
     * @param url {String} Private claim URL. Do not log or cache.
     * @param qrUrl {String} 
     * @param expiresAt {Date} 
     */
    constructor(id, tokenPrefix, url, qrUrl, expiresAt) { 
        
        IssuedPromoLink.initialize(this, id, tokenPrefix, url, qrUrl, expiresAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, tokenPrefix, url, qrUrl, expiresAt) { 
        obj['id'] = id;
        obj['token_prefix'] = tokenPrefix;
        obj['url'] = url;
        obj['qr_url'] = qrUrl;
        obj['expires_at'] = expiresAt;
    }

    /**
     * Constructs a <code>IssuedPromoLink</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssuedPromoLink} obj Optional instance to populate.
     * @return {module:model/IssuedPromoLink} The populated <code>IssuedPromoLink</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssuedPromoLink();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('token_prefix')) {
                obj['token_prefix'] = ApiClient.convertToType(data['token_prefix'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('qr_url')) {
                obj['qr_url'] = ApiClient.convertToType(data['qr_url'], 'String');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IssuedPromoLink</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IssuedPromoLink</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IssuedPromoLink.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['token_prefix'] && !(typeof data['token_prefix'] === 'string' || data['token_prefix'] instanceof String)) {
            throw new Error("Expected the field `token_prefix` to be a primitive type in the JSON string but got " + data['token_prefix']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['qr_url'] && !(typeof data['qr_url'] === 'string' || data['qr_url'] instanceof String)) {
            throw new Error("Expected the field `qr_url` to be a primitive type in the JSON string but got " + data['qr_url']);
        }

        return true;
    }


}

IssuedPromoLink.RequiredProperties = ["id", "token_prefix", "url", "qr_url", "expires_at"];

/**
 * @member {String} id
 */
IssuedPromoLink.prototype['id'] = undefined;

/**
 * @member {String} token_prefix
 */
IssuedPromoLink.prototype['token_prefix'] = undefined;

/**
 * Private claim URL. Do not log or cache.
 * @member {String} url
 */
IssuedPromoLink.prototype['url'] = undefined;

/**
 * @member {String} qr_url
 */
IssuedPromoLink.prototype['qr_url'] = undefined;

/**
 * @member {Date} expires_at
 */
IssuedPromoLink.prototype['expires_at'] = undefined;






export default IssuedPromoLink;

