/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IssuedPromoLink from './IssuedPromoLink';

/**
 * The IssuePromoLinkBatchResponseAllOfData model module.
 * @module model/IssuePromoLinkBatchResponseAllOfData
 * @version 1.0.0
 */
class IssuePromoLinkBatchResponseAllOfData {
    /**
     * Constructs a new <code>IssuePromoLinkBatchResponseAllOfData</code>.
     * @alias module:model/IssuePromoLinkBatchResponseAllOfData
     * @param batchId {String} 
     * @param sourceId {String} 
     * @param allocation {Number} 
     * @param links {Array.<module:model/IssuedPromoLink>} 
     */
    constructor(batchId, sourceId, allocation, links) { 
        
        IssuePromoLinkBatchResponseAllOfData.initialize(this, batchId, sourceId, allocation, links);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, batchId, sourceId, allocation, links) { 
        obj['batch_id'] = batchId;
        obj['source_id'] = sourceId;
        obj['allocation'] = allocation;
        obj['links'] = links;
    }

    /**
     * Constructs a <code>IssuePromoLinkBatchResponseAllOfData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IssuePromoLinkBatchResponseAllOfData} obj Optional instance to populate.
     * @return {module:model/IssuePromoLinkBatchResponseAllOfData} The populated <code>IssuePromoLinkBatchResponseAllOfData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IssuePromoLinkBatchResponseAllOfData();

            if (data.hasOwnProperty('batch_id')) {
                obj['batch_id'] = ApiClient.convertToType(data['batch_id'], 'String');
            }
            if (data.hasOwnProperty('source_id')) {
                obj['source_id'] = ApiClient.convertToType(data['source_id'], 'String');
            }
            if (data.hasOwnProperty('allocation')) {
                obj['allocation'] = ApiClient.convertToType(data['allocation'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [IssuedPromoLink]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IssuePromoLinkBatchResponseAllOfData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IssuePromoLinkBatchResponseAllOfData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IssuePromoLinkBatchResponseAllOfData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['batch_id'] && !(typeof data['batch_id'] === 'string' || data['batch_id'] instanceof String)) {
            throw new Error("Expected the field `batch_id` to be a primitive type in the JSON string but got " + data['batch_id']);
        }
        // ensure the json data is a string
        if (data['source_id'] && !(typeof data['source_id'] === 'string' || data['source_id'] instanceof String)) {
            throw new Error("Expected the field `source_id` to be a primitive type in the JSON string but got " + data['source_id']);
        }
        if (data['links']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['links'])) {
                throw new Error("Expected the field `links` to be an array in the JSON data but got " + data['links']);
            }
            // validate the optional field `links` (array)
            for (const item of data['links']) {
                IssuedPromoLink.validateJSON(item);
            };
        }

        return true;
    }


}

IssuePromoLinkBatchResponseAllOfData.RequiredProperties = ["batch_id", "source_id", "allocation", "links"];

/**
 * @member {String} batch_id
 */
IssuePromoLinkBatchResponseAllOfData.prototype['batch_id'] = undefined;

/**
 * @member {String} source_id
 */
IssuePromoLinkBatchResponseAllOfData.prototype['source_id'] = undefined;

/**
 * @member {Number} allocation
 */
IssuePromoLinkBatchResponseAllOfData.prototype['allocation'] = undefined;

/**
 * @member {Array.<module:model/IssuedPromoLink>} links
 */
IssuePromoLinkBatchResponseAllOfData.prototype['links'] = undefined;






export default IssuePromoLinkBatchResponseAllOfData;

