/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import ResponseEnvelope from './ResponseEnvelope';

/**
 * The LeverageNotFoundError model module.
 * @module model/LeverageNotFoundError
 * @version 1.0.0
 */
export default class LeverageNotFoundError extends ResponseEnvelope {
  /**
   * Constructs a new <code>LeverageNotFoundError</code>.
   * @alias module:model/LeverageNotFoundError
   * @class
   * @extends module:model/ResponseEnvelope
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>LeverageNotFoundError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LeverageNotFoundError} obj Optional instance to populate.
   * @return {module:model/LeverageNotFoundError} The populated <code>LeverageNotFoundError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LeverageNotFoundError();
      ResponseEnvelope.constructFromObject(data, obj);
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} error
 */
LeverageNotFoundError.prototype.error = undefined;

