/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Candle from './Candle';
import Metadata from './Metadata';
import ResponseEnvelope from './ResponseEnvelope';

/**
 * The ListCandlesResponse model module.
 * @module model/ListCandlesResponse
 * @version 1.0.0
 */
export default class ListCandlesResponse extends ResponseEnvelope {
  /**
   * Constructs a new <code>ListCandlesResponse</code>.
   * @alias module:model/ListCandlesResponse
   * @class
   * @extends module:model/ResponseEnvelope
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ListCandlesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListCandlesResponse} obj Optional instance to populate.
   * @return {module:model/ListCandlesResponse} The populated <code>ListCandlesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListCandlesResponse();
      ResponseEnvelope.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [Candle]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Candle>} data
 */
ListCandlesResponse.prototype.data = undefined;

