/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import ResponseEnvelope from './ResponseEnvelope';
import Trade from './Trade';

/**
 * The ListTradeResponseEnvelope model module.
 * @module model/ListTradeResponseEnvelope
 * @version 1.0.0
 */
export default class ListTradeResponseEnvelope extends ResponseEnvelope {
  /**
   * Constructs a new <code>ListTradeResponseEnvelope</code>.
   * @alias module:model/ListTradeResponseEnvelope
   * @class
   * @extends module:model/ResponseEnvelope
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ListTradeResponseEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListTradeResponseEnvelope} obj Optional instance to populate.
   * @return {module:model/ListTradeResponseEnvelope} The populated <code>ListTradeResponseEnvelope</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListTradeResponseEnvelope();
      ResponseEnvelope.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [Trade]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Trade>} data
 */
ListTradeResponseEnvelope.prototype.data = undefined;

