/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import OrderBookDepth from './OrderBookDepth';
import ResponseEnvelope from './ResponseEnvelope';

/**
 * The ListOrderBookDepthResponseEnvelope model module.
 * @module model/ListOrderBookDepthResponseEnvelope
 * @version 1.0.0
 */
export default class ListOrderBookDepthResponseEnvelope extends ResponseEnvelope {
  /**
   * Constructs a new <code>ListOrderBookDepthResponseEnvelope</code>.
   * @alias module:model/ListOrderBookDepthResponseEnvelope
   * @class
   * @extends module:model/ResponseEnvelope
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ListOrderBookDepthResponseEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListOrderBookDepthResponseEnvelope} obj Optional instance to populate.
   * @return {module:model/ListOrderBookDepthResponseEnvelope} The populated <code>ListOrderBookDepthResponseEnvelope</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListOrderBookDepthResponseEnvelope();
      ResponseEnvelope.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = OrderBookDepth.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/OrderBookDepth} data
 */
ListOrderBookDepthResponseEnvelope.prototype.data = undefined;

