/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ListOrdersResponseEnvelope model module.
 * @module model/ListOrdersResponseEnvelope
 * @version 1.0.0
 */
export default class ListOrdersResponseEnvelope {
  /**
   * Constructs a new <code>ListOrdersResponseEnvelope</code>.
   * @alias module:model/ListOrdersResponseEnvelope
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ListOrdersResponseEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListOrdersResponseEnvelope} obj Optional instance to populate.
   * @return {module:model/ListOrdersResponseEnvelope} The populated <code>ListOrdersResponseEnvelope</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListOrdersResponseEnvelope();
    }
    return obj;
  }
}
