/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModuleBalance model module.
 * @module model/ModuleBalance
 * @version 1.0.0
 */
class ModuleBalance {
    /**
     * Constructs a new <code>ModuleBalance</code>.
     * @alias module:model/ModuleBalance
     * @param assetId {String} 
     * @param seq {Number} 
     * @param available {String} The available balance in the module for this asset
     * @param supplied {String} The total amount supplied to the module for this asset
     * @param virtual {String} Assets minted by virtual-borrowing, but not yet repaid
     * @param borrowed {String} The total amount borrowed from the supplied but not yet repaid
     */
    constructor(assetId, seq, available, supplied, virtual, borrowed) { 
        
        ModuleBalance.initialize(this, assetId, seq, available, supplied, virtual, borrowed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetId, seq, available, supplied, virtual, borrowed) { 
        obj['asset_id'] = assetId;
        obj['seq'] = seq;
        obj['available'] = available;
        obj['supplied'] = supplied;
        obj['virtual'] = virtual;
        obj['borrowed'] = borrowed;
    }

    /**
     * Constructs a <code>ModuleBalance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModuleBalance} obj Optional instance to populate.
     * @return {module:model/ModuleBalance} The populated <code>ModuleBalance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModuleBalance();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('seq')) {
                obj['seq'] = ApiClient.convertToType(data['seq'], 'Number');
            }
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'String');
            }
            if (data.hasOwnProperty('supplied')) {
                obj['supplied'] = ApiClient.convertToType(data['supplied'], 'String');
            }
            if (data.hasOwnProperty('virtual')) {
                obj['virtual'] = ApiClient.convertToType(data['virtual'], 'String');
            }
            if (data.hasOwnProperty('borrowed')) {
                obj['borrowed'] = ApiClient.convertToType(data['borrowed'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModuleBalance</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModuleBalance</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ModuleBalance.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is a string
        if (data['available'] && !(typeof data['available'] === 'string' || data['available'] instanceof String)) {
            throw new Error("Expected the field `available` to be a primitive type in the JSON string but got " + data['available']);
        }
        // ensure the json data is a string
        if (data['supplied'] && !(typeof data['supplied'] === 'string' || data['supplied'] instanceof String)) {
            throw new Error("Expected the field `supplied` to be a primitive type in the JSON string but got " + data['supplied']);
        }
        // ensure the json data is a string
        if (data['virtual'] && !(typeof data['virtual'] === 'string' || data['virtual'] instanceof String)) {
            throw new Error("Expected the field `virtual` to be a primitive type in the JSON string but got " + data['virtual']);
        }
        // ensure the json data is a string
        if (data['borrowed'] && !(typeof data['borrowed'] === 'string' || data['borrowed'] instanceof String)) {
            throw new Error("Expected the field `borrowed` to be a primitive type in the JSON string but got " + data['borrowed']);
        }

        return true;
    }


}

ModuleBalance.RequiredProperties = ["asset_id", "seq", "available", "supplied", "virtual", "borrowed"];

/**
 * @member {String} asset_id
 */
ModuleBalance.prototype['asset_id'] = undefined;

/**
 * @member {Number} seq
 */
ModuleBalance.prototype['seq'] = undefined;

/**
 * The available balance in the module for this asset
 * @member {String} available
 */
ModuleBalance.prototype['available'] = undefined;

/**
 * The total amount supplied to the module for this asset
 * @member {String} supplied
 */
ModuleBalance.prototype['supplied'] = undefined;

/**
 * Assets minted by virtual-borrowing, but not yet repaid
 * @member {String} virtual
 */
ModuleBalance.prototype['virtual'] = undefined;

/**
 * The total amount borrowed from the supplied but not yet repaid
 * @member {String} borrowed
 */
ModuleBalance.prototype['borrowed'] = undefined;






export default ModuleBalance;

