/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderBookBalance model module.
 * @module model/OrderBookBalance
 * @version 1.0.0
 */
export default class OrderBookBalance {
  /**
   * Constructs a new <code>OrderBookBalance</code>.
   * @alias module:model/OrderBookBalance
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderBookBalance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderBookBalance} obj Optional instance to populate.
   * @return {module:model/OrderBookBalance} The populated <code>OrderBookBalance</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderBookBalance();
      if (data.hasOwnProperty('order_book_id'))
        obj.orderBookId = ApiClient.convertToType(data['order_book_id'], Object);
      if (data.hasOwnProperty('base_quantity'))
        obj.baseQuantity = ApiClient.convertToType(data['base_quantity'], Object);
      if (data.hasOwnProperty('quote_quantity'))
        obj.quoteQuantity = ApiClient.convertToType(data['quote_quantity'], Object);
      if (data.hasOwnProperty('shares_quantity'))
        obj.sharesQuantity = ApiClient.convertToType(data['shares_quantity'], Object);
    }
    return obj;
  }
}

/**
 * The ID of the order book.
 * @member {Object} orderBookId
 */
OrderBookBalance.prototype.orderBookId = undefined;

/**
 * The quantity of the base asset.
 * @member {Object} baseQuantity
 */
OrderBookBalance.prototype.baseQuantity = undefined;

/**
 * The quantity of the quote asset.
 * @member {Object} quoteQuantity
 */
OrderBookBalance.prototype.quoteQuantity = undefined;

/**
 * The quantity of pool shares.
 * @member {Object} sharesQuantity
 */
OrderBookBalance.prototype.sharesQuantity = undefined;

