/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderBookDepth model module.
 * @module model/OrderBookDepth
 * @version 1.0.0
 */
export default class OrderBookDepth {
  /**
   * Constructs a new <code>OrderBookDepth</code>.
   * @alias module:model/OrderBookDepth
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderBookDepth</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderBookDepth} obj Optional instance to populate.
   * @return {module:model/OrderBookDepth} The populated <code>OrderBookDepth</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderBookDepth();
      if (data.hasOwnProperty('order_book_id'))
        obj.orderBookId = ApiClient.convertToType(data['order_book_id'], Object);
      if (data.hasOwnProperty('bids'))
        obj.bids = ApiClient.convertToType(data['bids'], Object);
      if (data.hasOwnProperty('asks'))
        obj.asks = ApiClient.convertToType(data['asks'], Object);
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} orderBookId
 */
OrderBookDepth.prototype.orderBookId = undefined;

/**
 * @member {Object} bids
 */
OrderBookDepth.prototype.bids = undefined;

/**
 * @member {Object} asks
 */
OrderBookDepth.prototype.asks = undefined;

/**
 * @member {Object} timestamp
 */
OrderBookDepth.prototype.timestamp = undefined;

