/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderbookStats model module.
 * @module model/OrderbookStats
 * @version 1.0.0
 */
export default class OrderbookStats {
  /**
   * Constructs a new <code>OrderbookStats</code>.
   * @alias module:model/OrderbookStats
   * @class
   * @param orderBookId {Object} 
   * @param openPrice {Object} Open price of the orderbook
   * @param lastPrice {Object} Price of the most recent executed trade.
   * @param high24h {Object} Highest price of the orderbook in the last 24 hours.
   * @param low24h {Object} Lowest price of the orderbook in the last 24 hours.
   * @param change24h {Object} Change in price of the orderbook in the last 24 hours.
   * @param changePct24h {Object} Change percentage in price of the orderbook in the last 24 hours.
   * @param volume24hBase {Object} Total volume of the orderbook in the last 24 hours.
   * @param volume24hUsd {Object} Total volume of the orderbook in the last 24 hours in USD.
   */
  constructor(orderBookId, openPrice, lastPrice, high24h, low24h, change24h, changePct24h, volume24hBase, volume24hUsd) {
    this.orderBookId = orderBookId;
    this.openPrice = openPrice;
    this.lastPrice = lastPrice;
    this.high24h = high24h;
    this.low24h = low24h;
    this.change24h = change24h;
    this.changePct24h = changePct24h;
    this.volume24hBase = volume24hBase;
    this.volume24hUsd = volume24hUsd;
  }

  /**
   * Constructs a <code>OrderbookStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderbookStats} obj Optional instance to populate.
   * @return {module:model/OrderbookStats} The populated <code>OrderbookStats</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderbookStats();
      if (data.hasOwnProperty('order_book_id'))
        obj.orderBookId = ApiClient.convertToType(data['order_book_id'], Object);
      if (data.hasOwnProperty('open_price'))
        obj.openPrice = ApiClient.convertToType(data['open_price'], Object);
      if (data.hasOwnProperty('last_price'))
        obj.lastPrice = ApiClient.convertToType(data['last_price'], Object);
      if (data.hasOwnProperty('high_24h'))
        obj.high24h = ApiClient.convertToType(data['high_24h'], Object);
      if (data.hasOwnProperty('low_24h'))
        obj.low24h = ApiClient.convertToType(data['low_24h'], Object);
      if (data.hasOwnProperty('change_24h'))
        obj.change24h = ApiClient.convertToType(data['change_24h'], Object);
      if (data.hasOwnProperty('change_pct_24h'))
        obj.changePct24h = ApiClient.convertToType(data['change_pct_24h'], Object);
      if (data.hasOwnProperty('volume_24h_base'))
        obj.volume24hBase = ApiClient.convertToType(data['volume_24h_base'], Object);
      if (data.hasOwnProperty('volume_24h_usd'))
        obj.volume24hUsd = ApiClient.convertToType(data['volume_24h_usd'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} orderBookId
 */
OrderbookStats.prototype.orderBookId = undefined;

/**
 * Open price of the orderbook
 * @member {Object} openPrice
 */
OrderbookStats.prototype.openPrice = undefined;

/**
 * Price of the most recent executed trade.
 * @member {Object} lastPrice
 */
OrderbookStats.prototype.lastPrice = undefined;

/**
 * Highest price of the orderbook in the last 24 hours.
 * @member {Object} high24h
 */
OrderbookStats.prototype.high24h = undefined;

/**
 * Lowest price of the orderbook in the last 24 hours.
 * @member {Object} low24h
 */
OrderbookStats.prototype.low24h = undefined;

/**
 * Change in price of the orderbook in the last 24 hours.
 * @member {Object} change24h
 */
OrderbookStats.prototype.change24h = undefined;

/**
 * Change percentage in price of the orderbook in the last 24 hours.
 * @member {Object} changePct24h
 */
OrderbookStats.prototype.changePct24h = undefined;

/**
 * Total volume of the orderbook in the last 24 hours.
 * @member {Object} volume24hBase
 */
OrderbookStats.prototype.volume24hBase = undefined;

/**
 * Total volume of the orderbook in the last 24 hours in USD.
 * @member {Object} volume24hUsd
 */
OrderbookStats.prototype.volume24hUsd = undefined;

