/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderBookTerminateResponse model module.
 * @module model/OrderBookTerminateResponse
 * @version 1.0.0
 */
export default class OrderBookTerminateResponse {
  /**
   * Constructs a new <code>OrderBookTerminateResponse</code>.
   * @alias module:model/OrderBookTerminateResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderBookTerminateResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderBookTerminateResponse} obj Optional instance to populate.
   * @return {module:model/OrderBookTerminateResponse} The populated <code>OrderBookTerminateResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderBookTerminateResponse();
    }
    return obj;
  }
}
