/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PayLeverageAccruedInterest model module.
 * @module model/PayLeverageAccruedInterest
 * @version 1.0.0
 */
export default class PayLeverageAccruedInterest {
  /**
   * Constructs a new <code>PayLeverageAccruedInterest</code>.
   * @alias module:model/PayLeverageAccruedInterest
   * @class
   * @param transactionId {Object} 
   * @param assetId {Object} 
   * @param positionId {Object} 
   * @param currentAccruedInterestUsd {Object} 
   */
  constructor(transactionId, assetId, positionId, currentAccruedInterestUsd) {
    this.transactionId = transactionId;
    this.assetId = assetId;
    this.positionId = positionId;
    this.currentAccruedInterestUsd = currentAccruedInterestUsd;
  }

  /**
   * Constructs a <code>PayLeverageAccruedInterest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayLeverageAccruedInterest} obj Optional instance to populate.
   * @return {module:model/PayLeverageAccruedInterest} The populated <code>PayLeverageAccruedInterest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PayLeverageAccruedInterest();
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], Object);
      if (data.hasOwnProperty('asset_id'))
        obj.assetId = ApiClient.convertToType(data['asset_id'], Object);
      if (data.hasOwnProperty('position_id'))
        obj.positionId = ApiClient.convertToType(data['position_id'], Object);
      if (data.hasOwnProperty('current_accrued_interest_usd'))
        obj.currentAccruedInterestUsd = ApiClient.convertToType(data['current_accrued_interest_usd'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} transactionId
 */
PayLeverageAccruedInterest.prototype.transactionId = undefined;

/**
 * @member {Object} assetId
 */
PayLeverageAccruedInterest.prototype.assetId = undefined;

/**
 * @member {Object} positionId
 */
PayLeverageAccruedInterest.prototype.positionId = undefined;

/**
 * @member {Object} currentAccruedInterestUsd
 */
PayLeverageAccruedInterest.prototype.currentAccruedInterestUsd = undefined;

