/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Margin from './Margin';

/**
 * The PLAsset model module.
 * @module model/PLAsset
 * @version 1.0.0
 */
export default class PLAsset {
  /**
   * Constructs a new <code>PLAsset</code>.
   * @alias module:model/PLAsset
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PLAsset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PLAsset} obj Optional instance to populate.
   * @return {module:model/PLAsset} The populated <code>PLAsset</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PLAsset();
      if (data.hasOwnProperty('symbol'))
        obj.symbol = ApiClient.convertToType(data['symbol'], Object);
      if (data.hasOwnProperty('side'))
        obj.side = ApiClient.convertToType(data['side'], Object);
      if (data.hasOwnProperty('avg_entry_price'))
        obj.avgEntryPrice = ApiClient.convertToType(data['avg_entry_price'], Object);
      if (data.hasOwnProperty('mark_price'))
        obj.markPrice = ApiClient.convertToType(data['mark_price'], Object);
      if (data.hasOwnProperty('liquidation_price'))
        obj.liquidationPrice = ApiClient.convertToType(data['liquidation_price'], Object);
      if (data.hasOwnProperty('available'))
        obj.available = ApiClient.convertToType(data['available'], Object);
      if (data.hasOwnProperty('borrowed'))
        obj.borrowed = ApiClient.convertToType(data['borrowed'], Object);
      if (data.hasOwnProperty('margin'))
        obj.margin = Margin.constructFromObject(data['margin']);
      if (data.hasOwnProperty('unrealized_pl'))
        obj.unrealizedPl = ApiClient.convertToType(data['unrealized_pl'], Object);
      if (data.hasOwnProperty('leverage_limit'))
        obj.leverageLimit = ApiClient.convertToType(data['leverage_limit'], Object);
      if (data.hasOwnProperty('tp'))
        obj.tp = ApiClient.convertToType(data['tp'], Object);
      if (data.hasOwnProperty('sl'))
        obj.sl = ApiClient.convertToType(data['sl'], Object);
    }
    return obj;
  }
}

/**
 * The symbol of the asset
 * @member {Object} symbol
 */
PLAsset.prototype.symbol = undefined;

/**
 * The side of the position (LONG or SHORT)
 * @member {Object} side
 */
PLAsset.prototype.side = undefined;

/**
 * The average entry price of the position
 * @member {Object} avgEntryPrice
 */
PLAsset.prototype.avgEntryPrice = undefined;

/**
 * The current mark price for the asset to calculate daily PL. This is usually the close price of the previous day
 * @member {Object} markPrice
 */
PLAsset.prototype.markPrice = undefined;

/**
 * The liquidation price of the position
 * @member {Object} liquidationPrice
 */
PLAsset.prototype.liquidationPrice = undefined;

/**
 * The available quantity in units of the asset
 * @member {Object} available
 */
PLAsset.prototype.available = undefined;

/**
 * The borrowed quantity in units of the asset
 * @member {Object} borrowed
 */
PLAsset.prototype.borrowed = undefined;

/**
 * @member {module:model/Margin} margin
 */
PLAsset.prototype.margin = undefined;

/**
 * The unrealized profit or loss of the position
 * @member {Object} unrealizedPl
 */
PLAsset.prototype.unrealizedPl = undefined;

/**
 * The leverage limit for the position
 * @member {Object} leverageLimit
 */
PLAsset.prototype.leverageLimit = undefined;

/**
 * The take profit price set for the position, if any
 * @member {Object} tp
 */
PLAsset.prototype.tp = undefined;

/**
 * The stop loss price set for the position, if any
 * @member {Object} sl
 */
PLAsset.prototype.sl = undefined;

