/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PositionAccount model module.
 * @module model/PositionAccount
 * @version 1.0.0
 */
class PositionAccount {
    /**
     * Constructs a new <code>PositionAccount</code>.
     * @alias module:model/PositionAccount
     * @param positionId {String} The ID of the position account
     * @param positionName {String} The name of the position account
     * @param isGlobal {Boolean} Whether the position account is the global or an isolated account
     */
    constructor(positionId, positionName, isGlobal) { 
        
        PositionAccount.initialize(this, positionId, positionName, isGlobal);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, positionId, positionName, isGlobal) { 
        obj['position_id'] = positionId;
        obj['position_name'] = positionName;
        obj['is_global'] = isGlobal;
    }

    /**
     * Constructs a <code>PositionAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PositionAccount} obj Optional instance to populate.
     * @return {module:model/PositionAccount} The populated <code>PositionAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PositionAccount();

            if (data.hasOwnProperty('position_id')) {
                obj['position_id'] = ApiClient.convertToType(data['position_id'], 'String');
            }
            if (data.hasOwnProperty('position_name')) {
                obj['position_name'] = ApiClient.convertToType(data['position_name'], 'String');
            }
            if (data.hasOwnProperty('is_global')) {
                obj['is_global'] = ApiClient.convertToType(data['is_global'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PositionAccount</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PositionAccount</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PositionAccount.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['position_id'] && !(typeof data['position_id'] === 'string' || data['position_id'] instanceof String)) {
            throw new Error("Expected the field `position_id` to be a primitive type in the JSON string but got " + data['position_id']);
        }
        // ensure the json data is a string
        if (data['position_name'] && !(typeof data['position_name'] === 'string' || data['position_name'] instanceof String)) {
            throw new Error("Expected the field `position_name` to be a primitive type in the JSON string but got " + data['position_name']);
        }

        return true;
    }


}

PositionAccount.RequiredProperties = ["position_id", "position_name", "is_global"];

/**
 * The ID of the position account
 * @member {String} position_id
 */
PositionAccount.prototype['position_id'] = undefined;

/**
 * The name of the position account
 * @member {String} position_name
 */
PositionAccount.prototype['position_name'] = undefined;

/**
 * Whether the position account is the global or an isolated account
 * @member {Boolean} is_global
 */
PositionAccount.prototype['is_global'] = undefined;






export default PositionAccount;

