/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Position model module.
 * @module model/Position
 * @version 1.0.0
 */
export default class Position {
  /**
   * Constructs a new <code>Position</code>.
   * @alias module:model/Position
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Position</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Position} obj Optional instance to populate.
   * @return {module:model/Position} The populated <code>Position</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Position();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('asset_id'))
        obj.assetId = ApiClient.convertToType(data['asset_id'], 'String');
      if (data.hasOwnProperty('seq'))
        obj.seq = ApiClient.convertToType(data['seq'], 'Number');
      if (data.hasOwnProperty('is_global'))
        obj.isGlobal = ApiClient.convertToType(data['is_global'], 'Boolean');
      if (data.hasOwnProperty('available'))
        obj.available = ApiClient.convertToType(data['available'], 'String');
      if (data.hasOwnProperty('locked'))
        obj.locked = ApiClient.convertToType(data['locked'], 'String');
      if (data.hasOwnProperty('supplied'))
        obj.supplied = ApiClient.convertToType(data['supplied'], 'String');
      if (data.hasOwnProperty('collateral'))
        obj.collateral = ApiClient.convertToType(data['collateral'], 'String');
      if (data.hasOwnProperty('supplied_collateral'))
        obj.suppliedCollateral = ApiClient.convertToType(data['supplied_collateral'], 'String');
      if (data.hasOwnProperty('borrowed'))
        obj.borrowed = ApiClient.convertToType(data['borrowed'], 'String');
      if (data.hasOwnProperty('impending_borrows'))
        obj.impendingBorrows = ApiClient.convertToType(data['impending_borrows'], 'String');
    }
    return obj;
  }
}

/**
 * The unique identifier for the position. Used, for example, when creating an order from a position, or deciding collateral should be transferred from position A to position B.
 * @member {String} id
 */
Position.prototype.id = undefined;

/**
 * @member {String} assetId
 */
Position.prototype.assetId = undefined;

/**
 * @member {Number} seq
 */
Position.prototype.seq = undefined;

/**
 * @member {Boolean} isGlobal
 */
Position.prototype.isGlobal = undefined;

/**
 * The available balance in the position for this asset that are not locked, supplied, or used as collateral
 * @member {String} available
 */
Position.prototype.available = undefined;

/**
 * The balance that has been reserved for a current order. If spent by the order, they are removed. If the order is cancelled, they are returned to the position's available balance.
 * @member {String} locked
 */
Position.prototype.locked = undefined;

/**
 * The balance that user has supplied to the leverage module. The user remains entitled to these assets and can withdraw them into their available balance.
 * @member {String} supplied
 */
Position.prototype.supplied = undefined;

/**
 * The balance that has been locked or supplied, but are marked as collateral to support borrow limits and can be consumed in case of liquidation. When unmarked as collateral, the balance returns to the available balance.
 * @member {String} collateral
 */
Position.prototype.collateral = undefined;

/**
 * The balance that have been supplied to the leverage module and marked as collateral. The user remains entitled to this balance and can withdraw it into the collateral balance, or unmark them as collateral and move them to the supplied balance.
 * @member {String} suppliedCollateral
 */
Position.prototype.suppliedCollateral = undefined;

/**
 * The total amount of debt outstanding for this position. The position's collateral + supplied_collateral must support a borrow limit sufficient to cover all borrowed assets. This position cannot be closed until all debt is fully repaid, i.e. borrowed = 0.
 * @member {String} borrowed
 */
Position.prototype.borrowed = undefined;

/**
 * The equivalent of locked balances, but for leveraged orders. If a user has an active order that would borrow assets as part of its input, then their borrow limit must be reduced until the order is executed or cancelled.
 * @member {String} impendingBorrows
 */
Position.prototype.impendingBorrows = undefined;

