/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PositionAccount model module.
 * @module model/PositionAccount
 * @version 1.0.0
 */
export default class PositionAccount {
  /**
   * Constructs a new <code>PositionAccount</code>.
   * @alias module:model/PositionAccount
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PositionAccount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PositionAccount} obj Optional instance to populate.
   * @return {module:model/PositionAccount} The populated <code>PositionAccount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PositionAccount();
      if (data.hasOwnProperty('position_id'))
        obj.positionId = ApiClient.convertToType(data['position_id'], Object);
      if (data.hasOwnProperty('position_name'))
        obj.positionName = ApiClient.convertToType(data['position_name'], Object);
      if (data.hasOwnProperty('is_global'))
        obj.isGlobal = ApiClient.convertToType(data['is_global'], Object);
    }
    return obj;
  }
}

/**
 * The ID of the position account
 * @member {Object} positionId
 */
PositionAccount.prototype.positionId = undefined;

/**
 * The name of the position account
 * @member {Object} positionName
 */
PositionAccount.prototype.positionName = undefined;

/**
 * Whether the position account is the global or an isolated account
 * @member {Object} isGlobal
 */
PositionAccount.prototype.isGlobal = undefined;

