/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The PriceLevel model module.
 * @module model/PriceLevel
 * @version 1.0.0
 */
export default class PriceLevel {
  /**
   * Constructs a new <code>PriceLevel</code>.
   * @alias module:model/PriceLevel
   * @class
   * @param price {Object} 
   * @param quantity {Object} 
   */
  constructor(price, quantity) {
    this.price = price;
    this.quantity = quantity;
  }

  /**
   * Constructs a <code>PriceLevel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PriceLevel} obj Optional instance to populate.
   * @return {module:model/PriceLevel} The populated <code>PriceLevel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PriceLevel();
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], Object);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} price
 */
PriceLevel.prototype.price = undefined;

/**
 * @member {Object} quantity
 */
PriceLevel.prototype.quantity = undefined;

