/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PromoLinkBatchSummary from './PromoLinkBatchSummary';

/**
 * The PromoLinkBatchListResponseAllOfData model module.
 * @module model/PromoLinkBatchListResponseAllOfData
 * @version 1.0.0
 */
class PromoLinkBatchListResponseAllOfData {
    /**
     * Constructs a new <code>PromoLinkBatchListResponseAllOfData</code>.
     * @alias module:model/PromoLinkBatchListResponseAllOfData
     * @param batches {Array.<module:model/PromoLinkBatchSummary>} 
     */
    constructor(batches) { 
        
        PromoLinkBatchListResponseAllOfData.initialize(this, batches);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, batches) { 
        obj['batches'] = batches;
    }

    /**
     * Constructs a <code>PromoLinkBatchListResponseAllOfData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PromoLinkBatchListResponseAllOfData} obj Optional instance to populate.
     * @return {module:model/PromoLinkBatchListResponseAllOfData} The populated <code>PromoLinkBatchListResponseAllOfData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PromoLinkBatchListResponseAllOfData();

            if (data.hasOwnProperty('batches')) {
                obj['batches'] = ApiClient.convertToType(data['batches'], [PromoLinkBatchSummary]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PromoLinkBatchListResponseAllOfData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PromoLinkBatchListResponseAllOfData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PromoLinkBatchListResponseAllOfData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['batches']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['batches'])) {
                throw new Error("Expected the field `batches` to be an array in the JSON data but got " + data['batches']);
            }
            // validate the optional field `batches` (array)
            for (const item of data['batches']) {
                PromoLinkBatchSummary.validateJSON(item);
            };
        }

        return true;
    }


}

PromoLinkBatchListResponseAllOfData.RequiredProperties = ["batches"];

/**
 * @member {Array.<module:model/PromoLinkBatchSummary>} batches
 */
PromoLinkBatchListResponseAllOfData.prototype['batches'] = undefined;






export default PromoLinkBatchListResponseAllOfData;

