/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoveTradingChallengeUsersRequest model module.
 * @module model/RemoveTradingChallengeUsersRequest
 * @version 1.0.0
 */
class RemoveTradingChallengeUsersRequest {
    /**
     * Constructs a new <code>RemoveTradingChallengeUsersRequest</code>.
     * @alias module:model/RemoveTradingChallengeUsersRequest
     * @param tradingChallengeId {String} 
     * @param users {Array.<String>} 
     */
    constructor(tradingChallengeId, users) { 
        
        RemoveTradingChallengeUsersRequest.initialize(this, tradingChallengeId, users);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tradingChallengeId, users) { 
        obj['trading_challenge_id'] = tradingChallengeId;
        obj['users'] = users;
    }

    /**
     * Constructs a <code>RemoveTradingChallengeUsersRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveTradingChallengeUsersRequest} obj Optional instance to populate.
     * @return {module:model/RemoveTradingChallengeUsersRequest} The populated <code>RemoveTradingChallengeUsersRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveTradingChallengeUsersRequest();

            if (data.hasOwnProperty('trading_challenge_id')) {
                obj['trading_challenge_id'] = ApiClient.convertToType(data['trading_challenge_id'], 'String');
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RemoveTradingChallengeUsersRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RemoveTradingChallengeUsersRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RemoveTradingChallengeUsersRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['trading_challenge_id'] && !(typeof data['trading_challenge_id'] === 'string' || data['trading_challenge_id'] instanceof String)) {
            throw new Error("Expected the field `trading_challenge_id` to be a primitive type in the JSON string but got " + data['trading_challenge_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['users'])) {
            throw new Error("Expected the field `users` to be an array in the JSON data but got " + data['users']);
        }

        return true;
    }


}

RemoveTradingChallengeUsersRequest.RequiredProperties = ["trading_challenge_id", "users"];

/**
 * @member {String} trading_challenge_id
 */
RemoveTradingChallengeUsersRequest.prototype['trading_challenge_id'] = undefined;

/**
 * @member {Array.<String>} users
 */
RemoveTradingChallengeUsersRequest.prototype['users'] = undefined;






export default RemoveTradingChallengeUsersRequest;

