/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Metadata from './Metadata';

/**
 * The ResponseEnvelope model module.
 * @module model/ResponseEnvelope
 * @version 1.0.0
 */
class ResponseEnvelope {
    /**
     * Constructs a new <code>ResponseEnvelope</code>.
     * Standard response envelope. For 2xx responses, &#39;data&#39; is set. For errors, &#39;error&#39; is set.
     * @alias module:model/ResponseEnvelope
     * @param metadata {module:model/Metadata} Metadata about the response, including status code and trace information.
     */
    constructor(metadata) { 
        
        ResponseEnvelope.initialize(this, metadata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metadata) { 
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>ResponseEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseEnvelope} obj Optional instance to populate.
     * @return {module:model/ResponseEnvelope} The populated <code>ResponseEnvelope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseEnvelope();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ResponseEnvelope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ResponseEnvelope</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ResponseEnvelope.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          Metadata.validateJSON(data['metadata']);
        }

        return true;
    }


}

ResponseEnvelope.RequiredProperties = ["metadata"];

/**
 * The response data. Present for successful (2xx) responses.
 * @member {Object} data
 */
ResponseEnvelope.prototype['data'] = undefined;

/**
 * The error message. Present for error (non-2xx) responses.
 * @member {String} error
 */
ResponseEnvelope.prototype['error'] = undefined;

/**
 * Metadata about the response, including status code and trace information.
 * @member {module:model/Metadata} metadata
 */
ResponseEnvelope.prototype['metadata'] = undefined;






export default ResponseEnvelope;

