/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RevokeAPIKeyData model module.
 * @module model/RevokeAPIKeyData
 * @version 1.0.0
 */
export default class RevokeAPIKeyData {
  /**
   * Constructs a new <code>RevokeAPIKeyData</code>.
   * @alias module:model/RevokeAPIKeyData
   * @class
   * @param userId {Object} 
   * @param keyId {Object} 
   * @param label {Object} 
   * @param isActive {Object} 
   */
  constructor(userId, keyId, label, isActive) {
    this.userId = userId;
    this.keyId = keyId;
    this.label = label;
    this.isActive = isActive;
  }

  /**
   * Constructs a <code>RevokeAPIKeyData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RevokeAPIKeyData} obj Optional instance to populate.
   * @return {module:model/RevokeAPIKeyData} The populated <code>RevokeAPIKeyData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RevokeAPIKeyData();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], Object);
      if (data.hasOwnProperty('key_id'))
        obj.keyId = ApiClient.convertToType(data['key_id'], Object);
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], Object);
      if (data.hasOwnProperty('is_active'))
        obj.isActive = ApiClient.convertToType(data['is_active'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} userId
 */
RevokeAPIKeyData.prototype.userId = undefined;

/**
 * @member {Object} keyId
 */
RevokeAPIKeyData.prototype.keyId = undefined;

/**
 * @member {Object} label
 */
RevokeAPIKeyData.prototype.label = undefined;

/**
 * @member {Object} isActive
 */
RevokeAPIKeyData.prototype.isActive = undefined;

