/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RevokeAPIKeyResponse model module.
 * @module model/RevokeAPIKeyResponse
 * @version 1.0.0
 */
export default class RevokeAPIKeyResponse {
  /**
   * Constructs a new <code>RevokeAPIKeyResponse</code>.
   * @alias module:model/RevokeAPIKeyResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RevokeAPIKeyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RevokeAPIKeyResponse} obj Optional instance to populate.
   * @return {module:model/RevokeAPIKeyResponse} The populated <code>RevokeAPIKeyResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RevokeAPIKeyResponse();
    }
    return obj;
  }
}
