/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import StreamPositionsEntry from './StreamPositionsEntry';

/**
 * The StreamPositionsResponse model module.
 * @module model/StreamPositionsResponse
 * @version 1.0.0
 */
export default class StreamPositionsResponse extends Array {
  /**
   * Constructs a new <code>StreamPositionsResponse</code>.
   * @alias module:model/StreamPositionsResponse
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>StreamPositionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamPositionsResponse} obj Optional instance to populate.
   * @return {module:model/StreamPositionsResponse} The populated <code>StreamPositionsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamPositionsResponse();
      ApiClient.constructFromObject(data, obj, 'StreamPositionsEntry');
    }
    return obj;
  }
}
