/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetPrice from './AssetPrice';

/**
 * The StreamAssetPricesResponse model module.
 * @module model/StreamAssetPricesResponse
 * @version 1.0.0
 */
class StreamAssetPricesResponse {
    /**
     * Constructs a new <code>StreamAssetPricesResponse</code>.
     * Map of asset prices keyed by asset ID. Format: {\&quot;asset_id\&quot;: {\&quot;asset_id\&quot;: \&quot;uuid\&quot;, \&quot;price\&quot;: \&quot;decimal\&quot;, \&quot;time\&quot;: \&quot;date-time\&quot;}}
     * @alias module:model/StreamAssetPricesResponse
     * @extends Object
     */
    constructor() { 
        
        StreamAssetPricesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StreamAssetPricesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StreamAssetPricesResponse} obj Optional instance to populate.
     * @return {module:model/StreamAssetPricesResponse} The populated <code>StreamAssetPricesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StreamAssetPricesResponse();

            ApiClient.constructFromObject(data, obj, 'AssetPrice');
            

        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StreamAssetPricesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StreamAssetPricesResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}








export default StreamAssetPricesResponse;

