/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Order from './Order';
import StreamEntry from './StreamEntry';

/**
 * The StreamOrdersEntry model module.
 * @module model/StreamOrdersEntry
 * @version 1.0.0
 */
export default class StreamOrdersEntry extends StreamEntry {
  /**
   * Constructs a new <code>StreamOrdersEntry</code>.
   * @alias module:model/StreamOrdersEntry
   * @class
   * @extends module:model/StreamEntry
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>StreamOrdersEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamOrdersEntry} obj Optional instance to populate.
   * @return {module:model/StreamOrdersEntry} The populated <code>StreamOrdersEntry</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamOrdersEntry();
      StreamEntry.constructFromObject(data, obj);
      if (data.hasOwnProperty('Val'))
        obj.val = Order.constructFromObject(data['Val']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Order} val
 */
StreamOrdersEntry.prototype.val = undefined;

