/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import StreamEntry from './StreamEntry';
import Transaction from './Transaction';

/**
 * The StreamTransactionsEntry model module.
 * @module model/StreamTransactionsEntry
 * @version 1.0.0
 */
export default class StreamTransactionsEntry extends StreamEntry {
  /**
   * Constructs a new <code>StreamTransactionsEntry</code>.
   * @alias module:model/StreamTransactionsEntry
   * @class
   * @extends module:model/StreamEntry
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>StreamTransactionsEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamTransactionsEntry} obj Optional instance to populate.
   * @return {module:model/StreamTransactionsEntry} The populated <code>StreamTransactionsEntry</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamTransactionsEntry();
      StreamEntry.constructFromObject(data, obj);
      if (data.hasOwnProperty('Val'))
        obj.val = Transaction.constructFromObject(data['Val']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Transaction} val
 */
StreamTransactionsEntry.prototype.val = undefined;

