/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Asset from './Asset';
import StreamEntry from './StreamEntry';

/**
 * The StreamAssetsEntry model module.
 * @module model/StreamAssetsEntry
 * @version 1.0.0
 */
class StreamAssetsEntry {
    /**
     * Constructs a new <code>StreamAssetsEntry</code>.
     * @alias module:model/StreamAssetsEntry
     * @implements module:model/StreamEntry
     * @param val {module:model/Asset} 
     * @param time {Date} The timestamp when the data was created
     */
    constructor(val, time) { 
        StreamEntry.initialize(this, val, time);
        StreamAssetsEntry.initialize(this, val, time);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, val, time) { 
        obj['Val'] = val;
        obj['Time'] = time;
    }

    /**
     * Constructs a <code>StreamAssetsEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StreamAssetsEntry} obj Optional instance to populate.
     * @return {module:model/StreamAssetsEntry} The populated <code>StreamAssetsEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StreamAssetsEntry();
            StreamEntry.constructFromObject(data, obj);

            if (data.hasOwnProperty('Val')) {
                obj['Val'] = Asset.constructFromObject(data['Val']);
            }
            if (data.hasOwnProperty('Time')) {
                obj['Time'] = ApiClient.convertToType(data['Time'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StreamAssetsEntry</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StreamAssetsEntry</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StreamAssetsEntry.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `Val`
        if (data['Val']) { // data not null
          Asset.validateJSON(data['Val']);
        }

        return true;
    }


}

StreamAssetsEntry.RequiredProperties = ["Val", "Time"];

/**
 * @member {module:model/Asset} Val
 */
StreamAssetsEntry.prototype['Val'] = undefined;

/**
 * The timestamp when the data was created
 * @member {Date} Time
 */
StreamAssetsEntry.prototype['Time'] = undefined;


// Implement StreamEntry interface:
/**
 * The data being streamed
 * @member {Object} Val
 */
StreamEntry.prototype['Val'] = undefined;
/**
 * The timestamp when the data was created
 * @member {Date} Time
 */
StreamEntry.prototype['Time'] = undefined;




export default StreamAssetsEntry;

