/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StreamUserCouponPaymentsEntry from './StreamUserCouponPaymentsEntry';
import UserCouponPaymentAssetSummary from './UserCouponPaymentAssetSummary';

/**
 * The StreamUserCouponPaymentsResponse model module.
 * @module model/StreamUserCouponPaymentsResponse
 * @version 1.0.0
 */
class StreamUserCouponPaymentsResponse {
    /**
     * Constructs a new <code>StreamUserCouponPaymentsResponse</code>.
     * @alias module:model/StreamUserCouponPaymentsResponse
     */
    constructor() { 
        
        StreamUserCouponPaymentsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StreamUserCouponPaymentsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StreamUserCouponPaymentsResponse} obj Optional instance to populate.
     * @return {module:model/StreamUserCouponPaymentsResponse} The populated <code>StreamUserCouponPaymentsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StreamUserCouponPaymentsResponse();

            if (data.hasOwnProperty('entries')) {
                obj['entries'] = ApiClient.convertToType(data['entries'], [StreamUserCouponPaymentsEntry]);
            }
            if (data.hasOwnProperty('summary_by_asset')) {
                obj['summary_by_asset'] = ApiClient.convertToType(data['summary_by_asset'], [UserCouponPaymentAssetSummary]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StreamUserCouponPaymentsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StreamUserCouponPaymentsResponse</code>.
     */
    static validateJSON(data) {
        if (data['entries']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['entries'])) {
                throw new Error("Expected the field `entries` to be an array in the JSON data but got " + data['entries']);
            }
            // validate the optional field `entries` (array)
            for (const item of data['entries']) {
                StreamUserCouponPaymentsEntry.validateJSON(item);
            };
        }
        if (data['summary_by_asset']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['summary_by_asset'])) {
                throw new Error("Expected the field `summary_by_asset` to be an array in the JSON data but got " + data['summary_by_asset']);
            }
            // validate the optional field `summary_by_asset` (array)
            for (const item of data['summary_by_asset']) {
                UserCouponPaymentAssetSummary.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/StreamUserCouponPaymentsEntry>} entries
 */
StreamUserCouponPaymentsResponse.prototype['entries'] = undefined;

/**
 * @member {Array.<module:model/UserCouponPaymentAssetSummary>} summary_by_asset
 */
StreamUserCouponPaymentsResponse.prototype['summary_by_asset'] = undefined;






export default StreamUserCouponPaymentsResponse;

