/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StreamPositionsEntry from './StreamPositionsEntry';

/**
 * The StreamPositionsResponse model module.
 * @module model/StreamPositionsResponse
 * @version 1.0.0
 */
class StreamPositionsResponse extends Array {
    /**
     * Constructs a new <code>StreamPositionsResponse</code>.
     * @alias module:model/StreamPositionsResponse
     * @extends Array
     */
    constructor() { 
        super();
        
        
        StreamPositionsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StreamPositionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StreamPositionsResponse} obj Optional instance to populate.
     * @return {module:model/StreamPositionsResponse} The populated <code>StreamPositionsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StreamPositionsResponse();

            ApiClient.constructFromObject(data, obj, 'StreamPositionsEntry');
            

        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StreamPositionsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StreamPositionsResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}








export default StreamPositionsResponse;

