/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import StreamOrderBookBalanceEntry from './StreamOrderBookBalanceEntry';

/**
 * The StreamOrderBookBalancesResponse model module.
 * @module model/StreamOrderBookBalancesResponse
 * @version 1.0.0
 */
export default class StreamOrderBookBalancesResponse extends Array {
  /**
   * Constructs a new <code>StreamOrderBookBalancesResponse</code>.
   * @alias module:model/StreamOrderBookBalancesResponse
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>StreamOrderBookBalancesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamOrderBookBalancesResponse} obj Optional instance to populate.
   * @return {module:model/StreamOrderBookBalancesResponse} The populated <code>StreamOrderBookBalancesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamOrderBookBalancesResponse();
      ApiClient.constructFromObject(data, obj, 'StreamOrderBookBalanceEntry');
    }
    return obj;
  }
}
