/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SupplyRequest model module.
 * @module model/SupplyRequest
 * @version 1.0.0
 */
class SupplyRequest {
    /**
     * Constructs a new <code>SupplyRequest</code>.
     * @alias module:model/SupplyRequest
     * @param positionId {String} 
     * @param assetId {String} 
     * @param quantity {String} 
     */
    constructor(positionId, assetId, quantity) { 
        
        SupplyRequest.initialize(this, positionId, assetId, quantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, positionId, assetId, quantity) { 
        obj['position_id'] = positionId;
        obj['asset_id'] = assetId;
        obj['quantity'] = quantity;
    }

    /**
     * Constructs a <code>SupplyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SupplyRequest} obj Optional instance to populate.
     * @return {module:model/SupplyRequest} The populated <code>SupplyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SupplyRequest();

            if (data.hasOwnProperty('position_id')) {
                obj['position_id'] = ApiClient.convertToType(data['position_id'], 'String');
            }
            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SupplyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SupplyRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SupplyRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['position_id'] && !(typeof data['position_id'] === 'string' || data['position_id'] instanceof String)) {
            throw new Error("Expected the field `position_id` to be a primitive type in the JSON string but got " + data['position_id']);
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is a string
        if (data['quantity'] && !(typeof data['quantity'] === 'string' || data['quantity'] instanceof String)) {
            throw new Error("Expected the field `quantity` to be a primitive type in the JSON string but got " + data['quantity']);
        }

        return true;
    }


}

SupplyRequest.RequiredProperties = ["position_id", "asset_id", "quantity"];

/**
 * @member {String} position_id
 */
SupplyRequest.prototype['position_id'] = undefined;

/**
 * @member {String} asset_id
 */
SupplyRequest.prototype['asset_id'] = undefined;

/**
 * @member {String} quantity
 */
SupplyRequest.prototype['quantity'] = undefined;






export default SupplyRequest;

