/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SupplyRequest model module.
 * @module model/SupplyRequest
 * @version 1.0.0
 */
export default class SupplyRequest {
  /**
   * Constructs a new <code>SupplyRequest</code>.
   * @alias module:model/SupplyRequest
   * @class
   * @param positionId {String} 
   * @param assetId {String} 
   * @param quantity {String} 
   */
  constructor(positionId, assetId, quantity) {
    this.positionId = positionId;
    this.assetId = assetId;
    this.quantity = quantity;
  }

  /**
   * Constructs a <code>SupplyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SupplyRequest} obj Optional instance to populate.
   * @return {module:model/SupplyRequest} The populated <code>SupplyRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SupplyRequest();
      if (data.hasOwnProperty('position_id'))
        obj.positionId = ApiClient.convertToType(data['position_id'], 'String');
      if (data.hasOwnProperty('asset_id'))
        obj.assetId = ApiClient.convertToType(data['asset_id'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} positionId
 */
SupplyRequest.prototype.positionId = undefined;

/**
 * @member {String} assetId
 */
SupplyRequest.prototype.assetId = undefined;

/**
 * @member {String} quantity
 */
SupplyRequest.prototype.quantity = undefined;

