/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Side from './Side';

/**
 * The Trade model module.
 * @module model/Trade
 * @version 1.0.0
 */
export default class Trade {
  /**
   * Constructs a new <code>Trade</code>.
   * @alias module:model/Trade
   * @class
   * @param transactionId {Object} 
   * @param asset0 {Object} 
   * @param createdAt {Object} 
   * @param orderBookId {Object} 
   * @param orderId {Object} 
   * @param orderSeq {Object} 
   * @param price {Object} 
   * @param quantity0 {Object} 
   * @param userId {Object} 
   * @param side {module:model/Side} 
   * @param aggressorIndicator {Object} If true, then this order is the aggressor (taker); otherwise it is the maker.
   */
  constructor(transactionId, asset0, createdAt, orderBookId, orderId, orderSeq, price, quantity0, userId, side, aggressorIndicator) {
    this.transactionId = transactionId;
    this.asset0 = asset0;
    this.createdAt = createdAt;
    this.orderBookId = orderBookId;
    this.orderId = orderId;
    this.orderSeq = orderSeq;
    this.price = price;
    this.quantity0 = quantity0;
    this.userId = userId;
    this.side = side;
    this.aggressorIndicator = aggressorIndicator;
  }

  /**
   * Constructs a <code>Trade</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Trade} obj Optional instance to populate.
   * @return {module:model/Trade} The populated <code>Trade</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Trade();
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], Object);
      if (data.hasOwnProperty('asset_0'))
        obj.asset0 = ApiClient.convertToType(data['asset_0'], Object);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], Object);
      if (data.hasOwnProperty('order_book_id'))
        obj.orderBookId = ApiClient.convertToType(data['order_book_id'], Object);
      if (data.hasOwnProperty('order_id'))
        obj.orderId = ApiClient.convertToType(data['order_id'], Object);
      if (data.hasOwnProperty('order_seq'))
        obj.orderSeq = ApiClient.convertToType(data['order_seq'], Object);
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], Object);
      if (data.hasOwnProperty('quantity_0'))
        obj.quantity0 = ApiClient.convertToType(data['quantity_0'], Object);
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], Object);
      if (data.hasOwnProperty('side'))
        obj.side = Side.constructFromObject(data['side']);
      if (data.hasOwnProperty('aggressor_indicator'))
        obj.aggressorIndicator = ApiClient.convertToType(data['aggressor_indicator'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} transactionId
 */
Trade.prototype.transactionId = undefined;

/**
 * @member {Object} asset0
 */
Trade.prototype.asset0 = undefined;

/**
 * @member {Object} createdAt
 */
Trade.prototype.createdAt = undefined;

/**
 * @member {Object} orderBookId
 */
Trade.prototype.orderBookId = undefined;

/**
 * @member {Object} orderId
 */
Trade.prototype.orderId = undefined;

/**
 * @member {Object} orderSeq
 */
Trade.prototype.orderSeq = undefined;

/**
 * @member {Object} price
 */
Trade.prototype.price = undefined;

/**
 * @member {Object} quantity0
 */
Trade.prototype.quantity0 = undefined;

/**
 * @member {Object} userId
 */
Trade.prototype.userId = undefined;

/**
 * @member {module:model/Side} side
 */
Trade.prototype.side = undefined;

/**
 * If true, then this order is the aggressor (taker); otherwise it is the maker.
 * @member {Object} aggressorIndicator
 */
Trade.prototype.aggressorIndicator = undefined;

