/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TradingChallengeType.
* @enum {}
* @readonly
*/
export default class TradingChallengeType {
    
        /**
         * value: "TOURNAMENT"
         * @const
         */
        "TOURNAMENT" = "TOURNAMENT";

    
        /**
         * value: "CASH"
         * @const
         */
        "CASH" = "CASH";

    

    /**
    * Returns a <code>TradingChallengeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TradingChallengeType} The enum <code>TradingChallengeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

