/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionsSettlement model module.
 * @module model/TransactionsSettlement
 * @version 1.0.0
 */
class TransactionsSettlement {
    /**
     * Constructs a new <code>TransactionsSettlement</code>.
     * @alias module:model/TransactionsSettlement
     * @param txId {String} 
     * @param userId {String} 
     * @param tenantId {String} 
     * @param positionId {String} 
     * @param txKind {String} 
     * @param quantityUsd {Number} 
     * @param createdAt {Date} 
     */
    constructor(txId, userId, tenantId, positionId, txKind, quantityUsd, createdAt) { 
        
        TransactionsSettlement.initialize(this, txId, userId, tenantId, positionId, txKind, quantityUsd, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, txId, userId, tenantId, positionId, txKind, quantityUsd, createdAt) { 
        obj['tx_id'] = txId;
        obj['user_id'] = userId;
        obj['tenant_id'] = tenantId;
        obj['position_id'] = positionId;
        obj['tx_kind'] = txKind;
        obj['quantity_usd'] = quantityUsd;
        obj['created_at'] = createdAt;
    }

    /**
     * Constructs a <code>TransactionsSettlement</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionsSettlement} obj Optional instance to populate.
     * @return {module:model/TransactionsSettlement} The populated <code>TransactionsSettlement</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionsSettlement();

            if (data.hasOwnProperty('tx_id')) {
                obj['tx_id'] = ApiClient.convertToType(data['tx_id'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('position_id')) {
                obj['position_id'] = ApiClient.convertToType(data['position_id'], 'String');
            }
            if (data.hasOwnProperty('tx_kind')) {
                obj['tx_kind'] = ApiClient.convertToType(data['tx_kind'], 'String');
            }
            if (data.hasOwnProperty('quantity_usd')) {
                obj['quantity_usd'] = ApiClient.convertToType(data['quantity_usd'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('settled_at')) {
                obj['settled_at'] = ApiClient.convertToType(data['settled_at'], 'Date');
            }
            if (data.hasOwnProperty('settled_by')) {
                obj['settled_by'] = ApiClient.convertToType(data['settled_by'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionsSettlement</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionsSettlement</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TransactionsSettlement.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['tx_id'] && !(typeof data['tx_id'] === 'string' || data['tx_id'] instanceof String)) {
            throw new Error("Expected the field `tx_id` to be a primitive type in the JSON string but got " + data['tx_id']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['tenant_id'] && !(typeof data['tenant_id'] === 'string' || data['tenant_id'] instanceof String)) {
            throw new Error("Expected the field `tenant_id` to be a primitive type in the JSON string but got " + data['tenant_id']);
        }
        // ensure the json data is a string
        if (data['position_id'] && !(typeof data['position_id'] === 'string' || data['position_id'] instanceof String)) {
            throw new Error("Expected the field `position_id` to be a primitive type in the JSON string but got " + data['position_id']);
        }
        // ensure the json data is a string
        if (data['tx_kind'] && !(typeof data['tx_kind'] === 'string' || data['tx_kind'] instanceof String)) {
            throw new Error("Expected the field `tx_kind` to be a primitive type in the JSON string but got " + data['tx_kind']);
        }
        // ensure the json data is a string
        if (data['quantity_usd'] && !(typeof data['quantity_usd'] === 'string' || data['quantity_usd'] instanceof String)) {
            throw new Error("Expected the field `quantity_usd` to be a primitive type in the JSON string but got " + data['quantity_usd']);
        }
        // ensure the json data is a string
        if (data['settled_by'] && !(typeof data['settled_by'] === 'string' || data['settled_by'] instanceof String)) {
            throw new Error("Expected the field `settled_by` to be a primitive type in the JSON string but got " + data['settled_by']);
        }

        return true;
    }


}

TransactionsSettlement.RequiredProperties = ["tx_id", "user_id", "tenant_id", "position_id", "tx_kind", "quantity_usd", "created_at"];

/**
 * @member {String} tx_id
 */
TransactionsSettlement.prototype['tx_id'] = undefined;

/**
 * @member {String} user_id
 */
TransactionsSettlement.prototype['user_id'] = undefined;

/**
 * @member {String} tenant_id
 */
TransactionsSettlement.prototype['tenant_id'] = undefined;

/**
 * @member {String} position_id
 */
TransactionsSettlement.prototype['position_id'] = undefined;

/**
 * @member {String} tx_kind
 */
TransactionsSettlement.prototype['tx_kind'] = undefined;

/**
 * @member {Number} quantity_usd
 */
TransactionsSettlement.prototype['quantity_usd'] = undefined;

/**
 * @member {Date} created_at
 */
TransactionsSettlement.prototype['created_at'] = undefined;

/**
 * @member {Date} settled_at
 */
TransactionsSettlement.prototype['settled_at'] = undefined;

/**
 * @member {String} settled_by
 */
TransactionsSettlement.prototype['settled_by'] = undefined;






export default TransactionsSettlement;

