/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TransactionKind from './TransactionKind';

/**
 * The Transaction model module.
 * @module model/Transaction
 * @version 1.0.0
 */
export default class Transaction {
  /**
   * Constructs a new <code>Transaction</code>.
   * @alias module:model/Transaction
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Transaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transaction} obj Optional instance to populate.
   * @return {module:model/Transaction} The populated <code>Transaction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Transaction();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], Object);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], Object);
      if (data.hasOwnProperty('kind'))
        obj.kind = TransactionKind.constructFromObject(data['kind']);
      if (data.hasOwnProperty('asset0'))
        obj.asset0 = ApiClient.convertToType(data['asset0'], Object);
      if (data.hasOwnProperty('quantity0'))
        obj.quantity0 = ApiClient.convertToType(data['quantity0'], Object);
      if (data.hasOwnProperty('quantity1'))
        obj.quantity1 = ApiClient.convertToType(data['quantity1'], Object);
      if (data.hasOwnProperty('asset1'))
        obj.asset1 = ApiClient.convertToType(data['asset1'], Object);
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} id
 */
Transaction.prototype.id = undefined;

/**
 * @member {Object} createdAt
 */
Transaction.prototype.createdAt = undefined;

/**
 * @member {module:model/TransactionKind} kind
 */
Transaction.prototype.kind = undefined;

/**
 * @member {Object} asset0
 */
Transaction.prototype.asset0 = undefined;

/**
 * @member {Object} quantity0
 */
Transaction.prototype.quantity0 = undefined;

/**
 * @member {Object} quantity1
 */
Transaction.prototype.quantity1 = undefined;

/**
 * @member {Object} asset1
 */
Transaction.prototype.asset1 = undefined;

/**
 * @member {Object} userId
 */
Transaction.prototype.userId = undefined;

