/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionsSettlementRequest model module.
 * @module model/TransactionsSettlementRequest
 * @version 1.0.0
 */
class TransactionsSettlementRequest {
    /**
     * Constructs a new <code>TransactionsSettlementRequest</code>.
     * @alias module:model/TransactionsSettlementRequest
     */
    constructor() { 
        
        TransactionsSettlementRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionsSettlementRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionsSettlementRequest} obj Optional instance to populate.
     * @return {module:model/TransactionsSettlementRequest} The populated <code>TransactionsSettlementRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionsSettlementRequest();

            if (data.hasOwnProperty('tx_ids')) {
                obj['tx_ids'] = ApiClient.convertToType(data['tx_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionsSettlementRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionsSettlementRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['tx_ids'])) {
            throw new Error("Expected the field `tx_ids` to be an array in the JSON data but got " + data['tx_ids']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} tx_ids
 */
TransactionsSettlementRequest.prototype['tx_ids'] = undefined;






export default TransactionsSettlementRequest;

