/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UnitePositionResponse model module.
 * @module model/UnitePositionResponse
 * @version 0.1.0
 */
export default class UnitePositionResponse {
  /**
   * Constructs a new <code>UnitePositionResponse</code>.
   * @alias module:model/UnitePositionResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UnitePositionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnitePositionResponse} obj Optional instance to populate.
   * @return {module:model/UnitePositionResponse} The populated <code>UnitePositionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UnitePositionResponse();
      if (data.hasOwnProperty('global_position_id'))
        obj.globalPositionId = ApiClient.convertToType(data['global_position_id'], 'String');
      if (data.hasOwnProperty('transaction_ids'))
        obj.transactionIds = ApiClient.convertToType(data['transaction_ids'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} globalPositionId
 */
UnitePositionResponse.prototype.globalPositionId = undefined;

/**
 * @member {Array.<String>} transactionIds
 */
UnitePositionResponse.prototype.transactionIds = undefined;

