/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UnitedPosition model module.
 * @module model/UnitedPosition
 * @version 1.0.0
 */
class UnitedPosition {
    /**
     * Constructs a new <code>UnitedPosition</code>.
     * @alias module:model/UnitedPosition
     * @param globalPositionId {String} 
     * @param transactionIds {Array.<String>} 
     */
    constructor(globalPositionId, transactionIds) { 
        
        UnitedPosition.initialize(this, globalPositionId, transactionIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, globalPositionId, transactionIds) { 
        obj['global_position_id'] = globalPositionId;
        obj['transaction_ids'] = transactionIds;
    }

    /**
     * Constructs a <code>UnitedPosition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UnitedPosition} obj Optional instance to populate.
     * @return {module:model/UnitedPosition} The populated <code>UnitedPosition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UnitedPosition();

            if (data.hasOwnProperty('global_position_id')) {
                obj['global_position_id'] = ApiClient.convertToType(data['global_position_id'], 'String');
            }
            if (data.hasOwnProperty('transaction_ids')) {
                obj['transaction_ids'] = ApiClient.convertToType(data['transaction_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UnitedPosition</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UnitedPosition</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UnitedPosition.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['global_position_id'] && !(typeof data['global_position_id'] === 'string' || data['global_position_id'] instanceof String)) {
            throw new Error("Expected the field `global_position_id` to be a primitive type in the JSON string but got " + data['global_position_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['transaction_ids'])) {
            throw new Error("Expected the field `transaction_ids` to be an array in the JSON data but got " + data['transaction_ids']);
        }

        return true;
    }


}

UnitedPosition.RequiredProperties = ["global_position_id", "transaction_ids"];

/**
 * @member {String} global_position_id
 */
UnitedPosition.prototype['global_position_id'] = undefined;

/**
 * @member {Array.<String>} transaction_ids
 */
UnitedPosition.prototype['transaction_ids'] = undefined;






export default UnitedPosition;

