/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UnitedPosition model module.
 * @module model/UnitedPosition
 * @version 1.0.0
 */
export default class UnitedPosition {
  /**
   * Constructs a new <code>UnitedPosition</code>.
   * @alias module:model/UnitedPosition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UnitedPosition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnitedPosition} obj Optional instance to populate.
   * @return {module:model/UnitedPosition} The populated <code>UnitedPosition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UnitedPosition();
      if (data.hasOwnProperty('global_position_id'))
        obj.globalPositionId = ApiClient.convertToType(data['global_position_id'], Object);
      if (data.hasOwnProperty('transaction_ids'))
        obj.transactionIds = ApiClient.convertToType(data['transaction_ids'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} globalPositionId
 */
UnitedPosition.prototype.globalPositionId = undefined;

/**
 * @member {Object} transactionIds
 */
UnitedPosition.prototype.transactionIds = undefined;

