/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateFieldBoolean from './UpdateFieldBoolean';
import UpdateFieldString from './UpdateFieldString';

/**
 * The UpdateUserConfigRequest model module.
 * @module model/UpdateUserConfigRequest
 * @version 1.0.0
 */
class UpdateUserConfigRequest {
    /**
     * Constructs a new <code>UpdateUserConfigRequest</code>.
     * Request body for PUT /user/{id}/config: update a user changeable details only. Other properties can only be changed by an admin following a manual request by the user.
     * @alias module:model/UpdateUserConfigRequest
     * @param timezone {module:model/UpdateFieldString} User's timezone, e.g., 'America/New_York', or an offset.
     */
    constructor(timezone) { 
        
        UpdateUserConfigRequest.initialize(this, timezone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, timezone) { 
        obj['timezone'] = timezone;
    }

    /**
     * Constructs a <code>UpdateUserConfigRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateUserConfigRequest} obj Optional instance to populate.
     * @return {module:model/UpdateUserConfigRequest} The populated <code>UpdateUserConfigRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUserConfigRequest();

            if (data.hasOwnProperty('photo_url')) {
                obj['photo_url'] = ApiClient.convertToType(data['photo_url'], UpdateFieldString);
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], UpdateFieldString);
            }
            if (data.hasOwnProperty('show_tutorial_cards')) {
                obj['show_tutorial_cards'] = ApiClient.convertToType(data['show_tutorial_cards'], UpdateFieldBoolean);
            }
            if (data.hasOwnProperty('notifications_enabled')) {
                obj['notifications_enabled'] = ApiClient.convertToType(data['notifications_enabled'], UpdateFieldBoolean);
            }
            if (data.hasOwnProperty('allow_email_notifications')) {
                obj['allow_email_notifications'] = ApiClient.convertToType(data['allow_email_notifications'], UpdateFieldBoolean);
            }
            if (data.hasOwnProperty('allow_liquidations_notifications')) {
                obj['allow_liquidations_notifications'] = ApiClient.convertToType(data['allow_liquidations_notifications'], UpdateFieldBoolean);
            }
            if (data.hasOwnProperty('allow_deposit_withdrawal_notifications')) {
                obj['allow_deposit_withdrawal_notifications'] = ApiClient.convertToType(data['allow_deposit_withdrawal_notifications'], UpdateFieldBoolean);
            }
            if (data.hasOwnProperty('allow_orders_notifications')) {
                obj['allow_orders_notifications'] = ApiClient.convertToType(data['allow_orders_notifications'], UpdateFieldBoolean);
            }
            if (data.hasOwnProperty('allow_copy_trading')) {
                obj['allow_copy_trading'] = ApiClient.convertToType(data['allow_copy_trading'], UpdateFieldBoolean);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateUserConfigRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateUserConfigRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateUserConfigRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `photo_url`
        if (data['photo_url']) { // data not null
          UpdateFieldString.validateJSON(data['photo_url']);
        }
        // validate the optional field `timezone`
        if (data['timezone']) { // data not null
          UpdateFieldString.validateJSON(data['timezone']);
        }
        // validate the optional field `show_tutorial_cards`
        if (data['show_tutorial_cards']) { // data not null
          UpdateFieldBoolean.validateJSON(data['show_tutorial_cards']);
        }
        // validate the optional field `notifications_enabled`
        if (data['notifications_enabled']) { // data not null
          UpdateFieldBoolean.validateJSON(data['notifications_enabled']);
        }
        // validate the optional field `allow_email_notifications`
        if (data['allow_email_notifications']) { // data not null
          UpdateFieldBoolean.validateJSON(data['allow_email_notifications']);
        }
        // validate the optional field `allow_liquidations_notifications`
        if (data['allow_liquidations_notifications']) { // data not null
          UpdateFieldBoolean.validateJSON(data['allow_liquidations_notifications']);
        }
        // validate the optional field `allow_deposit_withdrawal_notifications`
        if (data['allow_deposit_withdrawal_notifications']) { // data not null
          UpdateFieldBoolean.validateJSON(data['allow_deposit_withdrawal_notifications']);
        }
        // validate the optional field `allow_orders_notifications`
        if (data['allow_orders_notifications']) { // data not null
          UpdateFieldBoolean.validateJSON(data['allow_orders_notifications']);
        }
        // validate the optional field `allow_copy_trading`
        if (data['allow_copy_trading']) { // data not null
          UpdateFieldBoolean.validateJSON(data['allow_copy_trading']);
        }

        return true;
    }


}

UpdateUserConfigRequest.RequiredProperties = ["timezone"];

/**
 * Optional: URL of the user's profile photo, optional.
 * @member {module:model/UpdateFieldString} photo_url
 */
UpdateUserConfigRequest.prototype['photo_url'] = undefined;

/**
 * User's timezone, e.g., 'America/New_York', or an offset.
 * @member {module:model/UpdateFieldString} timezone
 */
UpdateUserConfigRequest.prototype['timezone'] = undefined;

/**
 * Optional: Whether to show the tutorial.
 * @member {module:model/UpdateFieldBoolean} show_tutorial_cards
 */
UpdateUserConfigRequest.prototype['show_tutorial_cards'] = undefined;

/**
 * Optional: Whether to show the notifications.
 * @member {module:model/UpdateFieldBoolean} notifications_enabled
 */
UpdateUserConfigRequest.prototype['notifications_enabled'] = undefined;

/**
 * Optional: Whether to allow email notifications.
 * @member {module:model/UpdateFieldBoolean} allow_email_notifications
 */
UpdateUserConfigRequest.prototype['allow_email_notifications'] = undefined;

/**
 * Optional: Whether to allow liquidations notifications.
 * @member {module:model/UpdateFieldBoolean} allow_liquidations_notifications
 */
UpdateUserConfigRequest.prototype['allow_liquidations_notifications'] = undefined;

/**
 * Optional: Whether to allow deposit/withdrawal notifications.
 * @member {module:model/UpdateFieldBoolean} allow_deposit_withdrawal_notifications
 */
UpdateUserConfigRequest.prototype['allow_deposit_withdrawal_notifications'] = undefined;

/**
 * Optional: Whether to allow orders notifications.
 * @member {module:model/UpdateFieldBoolean} allow_orders_notifications
 */
UpdateUserConfigRequest.prototype['allow_orders_notifications'] = undefined;

/**
 * Optional: Whether to allow copy trading.
 * @member {module:model/UpdateFieldBoolean} allow_copy_trading
 */
UpdateUserConfigRequest.prototype['allow_copy_trading'] = undefined;






export default UpdateUserConfigRequest;

