/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UpdateFieldDateTime model module.
 * @module model/UpdateFieldDateTime
 * @version 0.1.0
 */
export default class UpdateFieldDateTime {
  /**
   * Constructs a new <code>UpdateFieldDateTime</code>.
   * A generic struct to handle optional updates for date-time fields in user requests.
   * @alias module:model/UpdateFieldDateTime
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateFieldDateTime</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateFieldDateTime} obj Optional instance to populate.
   * @return {module:model/UpdateFieldDateTime} The populated <code>UpdateFieldDateTime</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateFieldDateTime();
      if (data.hasOwnProperty('update'))
        obj.update = ApiClient.convertToType(data['update'], 'Boolean');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Date');
    }
    return obj;
  }
}

/**
 * Whether to update the field.
 * @member {Boolean} update
 */
UpdateFieldDateTime.prototype.update = undefined;

/**
 * The new value to set for the field.
 * @member {Date} value
 */
UpdateFieldDateTime.prototype.value = undefined;

