/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UpdateOrderBookRequest model module.
 * @module model/UpdateOrderBookRequest
 * @version 1.0.0
 */
export default class UpdateOrderBookRequest {
  /**
   * Constructs a new <code>UpdateOrderBookRequest</code>.
   * @alias module:model/UpdateOrderBookRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UpdateOrderBookRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateOrderBookRequest} obj Optional instance to populate.
   * @return {module:model/UpdateOrderBookRequest} The populated <code>UpdateOrderBookRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateOrderBookRequest();
      if (data.hasOwnProperty('order_book_id'))
        obj.orderBookId = ApiClient.convertToType(data['order_book_id'], 'String');
      if (data.hasOwnProperty('display_name'))
        obj.displayName = ApiClient.convertToType(data['display_name'], 'String');
      if (data.hasOwnProperty('fee_factor'))
        obj.feeFactor = ApiClient.convertToType(data['fee_factor'], 'Number');
      if (data.hasOwnProperty('initial_assets_ratio'))
        obj.initialAssetsRatio = ApiClient.convertToType(data['initial_assets_ratio'], 'Number');
      if (data.hasOwnProperty('price_display_multiplier'))
        obj.priceDisplayMultiplier = ApiClient.convertToType(data['price_display_multiplier'], 'Number');
      if (data.hasOwnProperty('tick_size'))
        obj.tickSize = ApiClient.convertToType(data['tick_size'], 'Number');
      if (data.hasOwnProperty('base_quantity'))
        obj.baseQuantity = ApiClient.convertToType(data['base_quantity'], 'Number');
      if (data.hasOwnProperty('quote_quantity'))
        obj.quoteQuantity = ApiClient.convertToType(data['quote_quantity'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} orderBookId
 */
UpdateOrderBookRequest.prototype.orderBookId = undefined;

/**
 * @member {String} displayName
 */
UpdateOrderBookRequest.prototype.displayName = undefined;

/**
 * @member {Number} feeFactor
 */
UpdateOrderBookRequest.prototype.feeFactor = undefined;

/**
 * @member {Number} initialAssetsRatio
 */
UpdateOrderBookRequest.prototype.initialAssetsRatio = undefined;

/**
 * @member {Number} priceDisplayMultiplier
 */
UpdateOrderBookRequest.prototype.priceDisplayMultiplier = undefined;

/**
 * @member {Number} tickSize
 */
UpdateOrderBookRequest.prototype.tickSize = undefined;

/**
 * @member {Number} baseQuantity
 */
UpdateOrderBookRequest.prototype.baseQuantity = undefined;

/**
 * @member {Number} quoteQuantity
 */
UpdateOrderBookRequest.prototype.quoteQuantity = undefined;

