/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UpdateFieldBoolean model module.
 * @module model/UpdateFieldBoolean
 * @version 1.0.0
 */
export default class UpdateFieldBoolean {
  /**
   * Constructs a new <code>UpdateFieldBoolean</code>.
   * A generic struct to handle optional updates for boolean fields in user requests.
   * @alias module:model/UpdateFieldBoolean
   * @class
   * @param update {Object} Whether to update the field.
   */
  constructor(update) {
    this.update = update;
  }

  /**
   * Constructs a <code>UpdateFieldBoolean</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateFieldBoolean} obj Optional instance to populate.
   * @return {module:model/UpdateFieldBoolean} The populated <code>UpdateFieldBoolean</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateFieldBoolean();
      if (data.hasOwnProperty('update'))
        obj.update = ApiClient.convertToType(data['update'], Object);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], Object);
    }
    return obj;
  }
}

/**
 * Whether to update the field.
 * @member {Object} update
 */
UpdateFieldBoolean.prototype.update = undefined;

/**
 * The new value to set for the field.
 * @member {Object} value
 */
UpdateFieldBoolean.prototype.value = undefined;

