/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserExistsResponse model module.
 * @module model/UserExistsResponse
 * @version 1.0.0
 */
class UserExistsResponse {
    /**
     * Constructs a new <code>UserExistsResponse</code>.
     * @alias module:model/UserExistsResponse
     * @param emailExists {Boolean} 
     * @param firebaseSet {Boolean} 
     * @param shouldCreateUser {Boolean} 
     */
    constructor(emailExists, firebaseSet, shouldCreateUser) { 
        
        UserExistsResponse.initialize(this, emailExists, firebaseSet, shouldCreateUser);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, emailExists, firebaseSet, shouldCreateUser) { 
        obj['email_exists'] = emailExists;
        obj['firebase_set'] = firebaseSet;
        obj['should_create_user'] = shouldCreateUser;
    }

    /**
     * Constructs a <code>UserExistsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserExistsResponse} obj Optional instance to populate.
     * @return {module:model/UserExistsResponse} The populated <code>UserExistsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserExistsResponse();

            if (data.hasOwnProperty('email_exists')) {
                obj['email_exists'] = ApiClient.convertToType(data['email_exists'], 'Boolean');
            }
            if (data.hasOwnProperty('firebase_set')) {
                obj['firebase_set'] = ApiClient.convertToType(data['firebase_set'], 'Boolean');
            }
            if (data.hasOwnProperty('should_create_user')) {
                obj['should_create_user'] = ApiClient.convertToType(data['should_create_user'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserExistsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserExistsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserExistsResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

UserExistsResponse.RequiredProperties = ["email_exists", "firebase_set", "should_create_user"];

/**
 * @member {Boolean} email_exists
 */
UserExistsResponse.prototype['email_exists'] = undefined;

/**
 * @member {Boolean} firebase_set
 */
UserExistsResponse.prototype['firebase_set'] = undefined;

/**
 * @member {Boolean} should_create_user
 */
UserExistsResponse.prototype['should_create_user'] = undefined;






export default UserExistsResponse;

