/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import ResponseEnvelope from './ResponseEnvelope';
import UserInterest from './UserInterest';

/**
 * The UserInterestResponse model module.
 * @module model/UserInterestResponse
 * @version 1.0.0
 */
export default class UserInterestResponse extends ResponseEnvelope {
  /**
   * Constructs a new <code>UserInterestResponse</code>.
   * @alias module:model/UserInterestResponse
   * @class
   * @extends module:model/ResponseEnvelope
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>UserInterestResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserInterestResponse} obj Optional instance to populate.
   * @return {module:model/UserInterestResponse} The populated <code>UserInterestResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserInterestResponse();
      ResponseEnvelope.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = UserInterest.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/UserInterest} data
 */
UserInterestResponse.prototype.data = undefined;

