/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserConfig model module.
 * @module model/UserConfig
 * @version 1.0.0
 */
class UserConfig {
    /**
     * Constructs a new <code>UserConfig</code>.
     * @alias module:model/UserConfig
     * @param id {String} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     * @param showTutorialCards {Boolean} 
     * @param notificationsEnabled {Boolean} 
     * @param allowEmailNotifications {Boolean} 
     * @param allowLiquidationsNotifications {Boolean} 
     * @param allowDepositWithdrawalNotifications {Boolean} 
     * @param allowOrdersNotifications {Boolean} 
     * @param allowCopyTrading {Boolean} 
     */
    constructor(id, createdAt, updatedAt, showTutorialCards, notificationsEnabled, allowEmailNotifications, allowLiquidationsNotifications, allowDepositWithdrawalNotifications, allowOrdersNotifications, allowCopyTrading) { 
        
        UserConfig.initialize(this, id, createdAt, updatedAt, showTutorialCards, notificationsEnabled, allowEmailNotifications, allowLiquidationsNotifications, allowDepositWithdrawalNotifications, allowOrdersNotifications, allowCopyTrading);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, createdAt, updatedAt, showTutorialCards, notificationsEnabled, allowEmailNotifications, allowLiquidationsNotifications, allowDepositWithdrawalNotifications, allowOrdersNotifications, allowCopyTrading) { 
        obj['id'] = id;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
        obj['show_tutorial_cards'] = showTutorialCards;
        obj['notifications_enabled'] = notificationsEnabled;
        obj['allow_email_notifications'] = allowEmailNotifications;
        obj['allow_liquidations_notifications'] = allowLiquidationsNotifications;
        obj['allow_deposit_withdrawal_notifications'] = allowDepositWithdrawalNotifications;
        obj['allow_orders_notifications'] = allowOrdersNotifications;
        obj['allow_copy_trading'] = allowCopyTrading;
    }

    /**
     * Constructs a <code>UserConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserConfig} obj Optional instance to populate.
     * @return {module:model/UserConfig} The populated <code>UserConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserConfig();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('photo_url')) {
                obj['photo_url'] = ApiClient.convertToType(data['photo_url'], 'String');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('show_tutorial_cards')) {
                obj['show_tutorial_cards'] = ApiClient.convertToType(data['show_tutorial_cards'], 'Boolean');
            }
            if (data.hasOwnProperty('notifications_enabled')) {
                obj['notifications_enabled'] = ApiClient.convertToType(data['notifications_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('allow_email_notifications')) {
                obj['allow_email_notifications'] = ApiClient.convertToType(data['allow_email_notifications'], 'Boolean');
            }
            if (data.hasOwnProperty('allow_liquidations_notifications')) {
                obj['allow_liquidations_notifications'] = ApiClient.convertToType(data['allow_liquidations_notifications'], 'Boolean');
            }
            if (data.hasOwnProperty('allow_deposit_withdrawal_notifications')) {
                obj['allow_deposit_withdrawal_notifications'] = ApiClient.convertToType(data['allow_deposit_withdrawal_notifications'], 'Boolean');
            }
            if (data.hasOwnProperty('allow_orders_notifications')) {
                obj['allow_orders_notifications'] = ApiClient.convertToType(data['allow_orders_notifications'], 'Boolean');
            }
            if (data.hasOwnProperty('allow_copy_trading')) {
                obj['allow_copy_trading'] = ApiClient.convertToType(data['allow_copy_trading'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserConfig</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserConfig.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['photo_url'] && !(typeof data['photo_url'] === 'string' || data['photo_url'] instanceof String)) {
            throw new Error("Expected the field `photo_url` to be a primitive type in the JSON string but got " + data['photo_url']);
        }
        // ensure the json data is a string
        if (data['timezone'] && !(typeof data['timezone'] === 'string' || data['timezone'] instanceof String)) {
            throw new Error("Expected the field `timezone` to be a primitive type in the JSON string but got " + data['timezone']);
        }

        return true;
    }


}

UserConfig.RequiredProperties = ["id", "created_at", "updated_at", "show_tutorial_cards", "notifications_enabled", "allow_email_notifications", "allow_liquidations_notifications", "allow_deposit_withdrawal_notifications", "allow_orders_notifications", "allow_copy_trading"];

/**
 * @member {String} id
 */
UserConfig.prototype['id'] = undefined;

/**
 * @member {String} photo_url
 */
UserConfig.prototype['photo_url'] = undefined;

/**
 * User's timezone, e.g., 'America/New_York', or an offset.
 * @member {String} timezone
 */
UserConfig.prototype['timezone'] = undefined;

/**
 * @member {Date} created_at
 */
UserConfig.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
UserConfig.prototype['updated_at'] = undefined;

/**
 * @member {Boolean} show_tutorial_cards
 */
UserConfig.prototype['show_tutorial_cards'] = undefined;

/**
 * @member {Boolean} notifications_enabled
 */
UserConfig.prototype['notifications_enabled'] = undefined;

/**
 * @member {Boolean} allow_email_notifications
 */
UserConfig.prototype['allow_email_notifications'] = undefined;

/**
 * @member {Boolean} allow_liquidations_notifications
 */
UserConfig.prototype['allow_liquidations_notifications'] = undefined;

/**
 * @member {Boolean} allow_deposit_withdrawal_notifications
 */
UserConfig.prototype['allow_deposit_withdrawal_notifications'] = undefined;

/**
 * @member {Boolean} allow_orders_notifications
 */
UserConfig.prototype['allow_orders_notifications'] = undefined;

/**
 * @member {Boolean} allow_copy_trading
 */
UserConfig.prototype['allow_copy_trading'] = undefined;






export default UserConfig;

