/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import ResponseEnvelope from './ResponseEnvelope';
import UserValue from './UserValue';

/**
 * The UserValueResponseEnvelope model module.
 * @module model/UserValueResponseEnvelope
 * @version 1.0.0
 */
class UserValueResponseEnvelope {
    /**
     * Constructs a new <code>UserValueResponseEnvelope</code>.
     * @alias module:model/UserValueResponseEnvelope
     * @implements module:model/ResponseEnvelope
     * @param metadata {module:model/Metadata} Metadata about the response, including status code and trace information.
     */
    constructor(metadata) { 
        ResponseEnvelope.initialize(this, metadata);
        UserValueResponseEnvelope.initialize(this, metadata);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metadata) { 
        obj['metadata'] = metadata;
    }

    /**
     * Constructs a <code>UserValueResponseEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserValueResponseEnvelope} obj Optional instance to populate.
     * @return {module:model/UserValueResponseEnvelope} The populated <code>UserValueResponseEnvelope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserValueResponseEnvelope();
            ResponseEnvelope.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = UserValue.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Metadata);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserValueResponseEnvelope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserValueResponseEnvelope</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserValueResponseEnvelope.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          UserValue.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // validate the optional field `metadata`
        if (data['metadata']) { // data not null
          Metadata.validateJSON(data['metadata']);
        }

        return true;
    }


}

UserValueResponseEnvelope.RequiredProperties = ["metadata"];

/**
 * @member {module:model/UserValue} data
 */
UserValueResponseEnvelope.prototype['data'] = undefined;

/**
 * The error message. Present for error (non-2xx) responses.
 * @member {String} error
 */
UserValueResponseEnvelope.prototype['error'] = undefined;

/**
 * Metadata about the response, including status code and trace information.
 * @member {module:model/Metadata} metadata
 */
UserValueResponseEnvelope.prototype['metadata'] = undefined;


// Implement ResponseEnvelope interface:
/**
 * The response data. Present for successful (2xx) responses.
 * @member {Object} data
 */
ResponseEnvelope.prototype['data'] = undefined;
/**
 * The error message. Present for error (non-2xx) responses.
 * @member {String} error
 */
ResponseEnvelope.prototype['error'] = undefined;
/**
 * Metadata about the response, including status code and trace information.
 * @member {module:model/Metadata} metadata
 */
ResponseEnvelope.prototype['metadata'] = undefined;




export default UserValueResponseEnvelope;

