/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserConfig model module.
 * @module model/UserConfig
 * @version 1.0.0
 */
export default class UserConfig {
  /**
   * Constructs a new <code>UserConfig</code>.
   * @alias module:model/UserConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserConfig} obj Optional instance to populate.
   * @return {module:model/UserConfig} The populated <code>UserConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserConfig();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('photo_url'))
        obj.photoUrl = ApiClient.convertToType(data['photo_url'], 'String');
      if (data.hasOwnProperty('timezone'))
        obj.timezone = ApiClient.convertToType(data['timezone'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UserConfig.prototype.id = undefined;

/**
 * @member {String} photoUrl
 */
UserConfig.prototype.photoUrl = undefined;

/**
 * User's timezone, e.g., 'America/New_York', or an offset.
 * @member {String} timezone
 */
UserConfig.prototype.timezone = undefined;

/**
 * @member {Date} createdAt
 */
UserConfig.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
UserConfig.prototype.updatedAt = undefined;

