/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UserRole.
* @enum {}
* @readonly
*/
export default class UserRole {
    
        /**
         * value: "PUBLIC"
         * @const
         */
        "PUBLIC" = "PUBLIC";

    
        /**
         * value: "SELF"
         * @const
         */
        "SELF" = "SELF";

    
        /**
         * value: "ADMIN"
         * @const
         */
        "ADMIN" = "ADMIN";

    
        /**
         * value: "BOND_PROVIDER"
         * @const
         */
        "BOND_PROVIDER" = "BOND_PROVIDER";

    
        /**
         * value: "LIQUIDITY_PROVIDER"
         * @const
         */
        "LIQUIDITY_PROVIDER" = "LIQUIDITY_PROVIDER";

    
        /**
         * value: "TRADER"
         * @const
         */
        "TRADER" = "TRADER";

    
        /**
         * value: "INTEGRATOR"
         * @const
         */
        "INTEGRATOR" = "INTEGRATOR";

    

    /**
    * Returns a <code>UserRole</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UserRole} The enum <code>UserRole</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

