/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 0.1.0
 */
export default class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('closed_at'))
        obj.closedAt = ApiClient.convertToType(data['closed_at'], 'Date');
      if (data.hasOwnProperty('disabled_at'))
        obj.disabledAt = ApiClient.convertToType(data['disabled_at'], 'Date');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('native_asset_id'))
        obj.nativeAssetId = ApiClient.convertToType(data['native_asset_id'], 'String');
      if (data.hasOwnProperty('photo_url'))
        obj.photoUrl = ApiClient.convertToType(data['photo_url'], 'String');
      if (data.hasOwnProperty('provider'))
        obj.provider = ApiClient.convertToType(data['provider'], 'String');
      if (data.hasOwnProperty('provider_id'))
        obj.providerId = ApiClient.convertToType(data['provider_id'], 'String');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], ['String']);
      if (data.hasOwnProperty('timezone'))
        obj.timezone = ApiClient.convertToType(data['timezone'], 'String');
      if (data.hasOwnProperty('timezone_offset'))
        obj.timezoneOffset = ApiClient.convertToType(data['timezone_offset'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
User.prototype.id = undefined;

/**
 * @member {Date} closedAt
 */
User.prototype.closedAt = undefined;

/**
 * @member {Date} disabledAt
 */
User.prototype.disabledAt = undefined;

/**
 * @member {String} email
 */
User.prototype.email = undefined;

/**
 * @member {String} name
 */
User.prototype.name = undefined;

/**
 * @member {String} nativeAssetId
 */
User.prototype.nativeAssetId = undefined;

/**
 * @member {String} photoUrl
 */
User.prototype.photoUrl = undefined;

/**
 * @member {String} provider
 */
User.prototype.provider = undefined;

/**
 * @member {String} providerId
 */
User.prototype.providerId = undefined;

/**
 * @member {Array.<String>} roles
 */
User.prototype.roles = undefined;

/**
 * User's timezone, e.g., 'America/New_York', or an offset.
 * @member {String} timezone
 */
User.prototype.timezone = undefined;

/**
 * timezone offset in seconds
 * @member {Number} timezoneOffset
 */
User.prototype.timezoneOffset = undefined;

