/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Web3WithdrawalStatus.
* @enum {}
* @readonly
*/
export default class Web3WithdrawalStatus {
    
        /**
         * value: "PENDING"
         * @const
         */
        "PENDING" = "PENDING";

    
        /**
         * value: "APPROVED_WITHOUT_FEE"
         * @const
         */
        "APPROVED_WITHOUT_FEE" = "APPROVED_WITHOUT_FEE";

    
        /**
         * value: "APPROVED"
         * @const
         */
        "APPROVED" = "APPROVED";

    
        /**
         * value: "BROADCAST"
         * @const
         */
        "BROADCAST" = "BROADCAST";

    
        /**
         * value: "SUBMITTED"
         * @const
         */
        "SUBMITTED" = "SUBMITTED";

    
        /**
         * value: "CONFIRMED"
         * @const
         */
        "CONFIRMED" = "CONFIRMED";

    
        /**
         * value: "REJECTED"
         * @const
         */
        "REJECTED" = "REJECTED";

    
        /**
         * value: "FAILED"
         * @const
         */
        "FAILED" = "FAILED";

    

    /**
    * Returns a <code>Web3WithdrawalStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Web3WithdrawalStatus} The enum <code>Web3WithdrawalStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

