/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Metadata from './Metadata';
import ResponseEnvelope from './ResponseEnvelope';
import Withdraw from './Withdraw';

/**
 * The WithdrawResponseEnvelope model module.
 * @module model/WithdrawResponseEnvelope
 * @version 1.0.0
 */
export default class WithdrawResponseEnvelope extends ResponseEnvelope {
  /**
   * Constructs a new <code>WithdrawResponseEnvelope</code>.
   * @alias module:model/WithdrawResponseEnvelope
   * @class
   * @extends module:model/ResponseEnvelope
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>WithdrawResponseEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WithdrawResponseEnvelope} obj Optional instance to populate.
   * @return {module:model/WithdrawResponseEnvelope} The populated <code>WithdrawResponseEnvelope</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WithdrawResponseEnvelope();
      ResponseEnvelope.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = Withdraw.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Withdraw} data
 */
WithdrawResponseEnvelope.prototype.data = undefined;

