/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import WithdrawalStatus from './WithdrawalStatus';

/**
 * The WithdrawalInitiation model module.
 * @module model/WithdrawalInitiation
 * @version 1.0.0
 */
export default class WithdrawalInitiation {
  /**
   * Constructs a new <code>WithdrawalInitiation</code>.
   * @alias module:model/WithdrawalInitiation
   * @class
   * @param withdrawalId {Object} 
   * @param userId {Object} 
   * @param positionId {Object} 
   * @param assetId {Object} 
   * @param quantity {Object} 
   * @param status {module:model/WithdrawalStatus} 
   * @param createdAt {Object} 
   * @param createdBy {Object} 
   * @param updatedAt {Object} 
   * @param updatedBy {Object} 
   * @param reason {Object} 
   */
  constructor(withdrawalId, userId, positionId, assetId, quantity, status, createdAt, createdBy, updatedAt, updatedBy, reason) {
    this.withdrawalId = withdrawalId;
    this.userId = userId;
    this.positionId = positionId;
    this.assetId = assetId;
    this.quantity = quantity;
    this.status = status;
    this.createdAt = createdAt;
    this.createdBy = createdBy;
    this.updatedAt = updatedAt;
    this.updatedBy = updatedBy;
    this.reason = reason;
  }

  /**
   * Constructs a <code>WithdrawalInitiation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WithdrawalInitiation} obj Optional instance to populate.
   * @return {module:model/WithdrawalInitiation} The populated <code>WithdrawalInitiation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WithdrawalInitiation();
      if (data.hasOwnProperty('withdrawal_id'))
        obj.withdrawalId = ApiClient.convertToType(data['withdrawal_id'], Object);
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], Object);
      if (data.hasOwnProperty('position_id'))
        obj.positionId = ApiClient.convertToType(data['position_id'], Object);
      if (data.hasOwnProperty('asset_id'))
        obj.assetId = ApiClient.convertToType(data['asset_id'], Object);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], Object);
      if (data.hasOwnProperty('status'))
        obj.status = WithdrawalStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], Object);
      if (data.hasOwnProperty('created_by'))
        obj.createdBy = ApiClient.convertToType(data['created_by'], Object);
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], Object);
      if (data.hasOwnProperty('updated_by'))
        obj.updatedBy = ApiClient.convertToType(data['updated_by'], Object);
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} withdrawalId
 */
WithdrawalInitiation.prototype.withdrawalId = undefined;

/**
 * @member {Object} userId
 */
WithdrawalInitiation.prototype.userId = undefined;

/**
 * @member {Object} positionId
 */
WithdrawalInitiation.prototype.positionId = undefined;

/**
 * @member {Object} assetId
 */
WithdrawalInitiation.prototype.assetId = undefined;

/**
 * @member {Object} quantity
 */
WithdrawalInitiation.prototype.quantity = undefined;

/**
 * @member {module:model/WithdrawalStatus} status
 */
WithdrawalInitiation.prototype.status = undefined;

/**
 * @member {Object} createdAt
 */
WithdrawalInitiation.prototype.createdAt = undefined;

/**
 * @member {Object} createdBy
 */
WithdrawalInitiation.prototype.createdBy = undefined;

/**
 * @member {Object} updatedAt
 */
WithdrawalInitiation.prototype.updatedAt = undefined;

/**
 * @member {Object} updatedBy
 */
WithdrawalInitiation.prototype.updatedBy = undefined;

/**
 * @member {Object} reason
 */
WithdrawalInitiation.prototype.reason = undefined;

