/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dora.AccountV2();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountV2', function() {
    it('should create an instance of AccountV2', function() {
      // uncomment below and update the code to test AccountV2
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be.a(Dora.AccountV2);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property assetId (base name: "asset_id")', function() {
      // uncomment below and update the code to test the property assetId
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property seq (base name: "seq")', function() {
      // uncomment below and update the code to test the property seq
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property isGlobal (base name: "is_global")', function() {
      // uncomment below and update the code to test the property isGlobal
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property available (base name: "available")', function() {
      // uncomment below and update the code to test the property available
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property locked (base name: "locked")', function() {
      // uncomment below and update the code to test the property locked
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property supplied (base name: "supplied")', function() {
      // uncomment below and update the code to test the property supplied
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property borrowed (base name: "borrowed")', function() {
      // uncomment below and update the code to test the property borrowed
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property impendingBorrows (base name: "impending_borrows")', function() {
      // uncomment below and update the code to test the property impendingBorrows
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property avgEntryPrice (base name: "avg_entry_price")', function() {
      // uncomment below and update the code to test the property avgEntryPrice
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property borrowLimit (base name: "borrow_limit")', function() {
      // uncomment below and update the code to test the property borrowLimit
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property liquidationThreshold (base name: "liquidation_threshold")', function() {
      // uncomment below and update the code to test the property liquidationThreshold
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property pendingWithdrawal (base name: "pending_withdrawal")', function() {
      // uncomment below and update the code to test the property pendingWithdrawal
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

    it('should have the property accountName (base name: "account_name")', function() {
      // uncomment below and update the code to test the property accountName
      //var instance = new Dora.AccountV2();
      //expect(instance).to.be();
    });

  });

}));
