/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dora.AffiliateAttribution();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AffiliateAttribution', function() {
    it('should create an instance of AffiliateAttribution', function() {
      // uncomment below and update the code to test AffiliateAttribution
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be.a(Dora.AffiliateAttribution);
    });

    it('should have the property referredUserId (base name: "referred_user_id")', function() {
      // uncomment below and update the code to test the property referredUserId
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

    it('should have the property programId (base name: "program_id")', function() {
      // uncomment below and update the code to test the property programId
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

    it('should have the property referrerId (base name: "referrer_id")', function() {
      // uncomment below and update the code to test the property referrerId
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

    it('should have the property referrerUserId (base name: "referrer_user_id")', function() {
      // uncomment below and update the code to test the property referrerUserId
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenant_id")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

    it('should have the property signupSource (base name: "signup_source")', function() {
      // uncomment below and update the code to test the property signupSource
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

    it('should have the property referralCode (base name: "referral_code")', function() {
      // uncomment below and update the code to test the property referralCode
      //var instance = new Dora.AffiliateAttribution();
      //expect(instance).to.be();
    });

  });

}));
