/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BalanceTransfer', function() {
      beforeEach(function() {
        instance = new Dora.BalanceTransfer();
      });

      it('should create an instance of BalanceTransfer', function() {
        // TODO: update the code to test BalanceTransfer
        expect(instance).to.be.a(Dora.BalanceTransfer);
      });

      it('should have the property fromPositionId (base name: "from_position_id")', function() {
        // TODO: update the code to test the property fromPositionId
        expect(instance).to.have.property('fromPositionId');
        // expect(instance.fromPositionId).to.be(expectedValueLiteral);
      });

      it('should have the property toPositionId (base name: "to_position_id")', function() {
        // TODO: update the code to test the property toPositionId
        expect(instance).to.have.property('toPositionId');
        // expect(instance.toPositionId).to.be(expectedValueLiteral);
      });

      it('should have the property transactionId (base name: "transaction_id")', function() {
        // TODO: update the code to test the property transactionId
        expect(instance).to.have.property('transactionId');
        // expect(instance.transactionId).to.be(expectedValueLiteral);
      });

    });
  });

}));
