/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ClosePositionRequest', function() {
      beforeEach(function() {
        instance = new Dora.ClosePositionRequest();
      });

      it('should create an instance of ClosePositionRequest', function() {
        // TODO: update the code to test ClosePositionRequest
        expect(instance).to.be.a(Dora.ClosePositionRequest);
      });

      it('should have the property positionId (base name: "position_id")', function() {
        // TODO: update the code to test the property positionId
        expect(instance).to.have.property('positionId');
        // expect(instance.positionId).to.be(expectedValueLiteral);
      });

      it('should have the property orderBookId (base name: "order_book_id")', function() {
        // TODO: update the code to test the property orderBookId
        expect(instance).to.have.property('orderBookId');
        // expect(instance.orderBookId).to.be(expectedValueLiteral);
      });

    });
  });

}));
