/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dora.CouponPayment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CouponPayment', function() {
    it('should create an instance of CouponPayment', function() {
      // uncomment below and update the code to test CouponPayment
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be.a(Dora.CouponPayment);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property assetId (base name: "asset_id")', function() {
      // uncomment below and update the code to test the property assetId
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property _yield (base name: "yield")', function() {
      // uncomment below and update the code to test the property _yield
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property startAt (base name: "start_at")', function() {
      // uncomment below and update the code to test the property startAt
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property endAt (base name: "end_at")', function() {
      // uncomment below and update the code to test the property endAt
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property payAt (base name: "pay_at")', function() {
      // uncomment below and update the code to test the property payAt
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property availableToPay (base name: "available_to_pay")', function() {
      // uncomment below and update the code to test the property availableToPay
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property completedAt (base name: "completed_at")', function() {
      // uncomment below and update the code to test the property completedAt
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property processEvery (base name: "process_every")', function() {
      // uncomment below and update the code to test the property processEvery
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

    it('should have the property lastProcessedAt (base name: "last_processed_at")', function() {
      // uncomment below and update the code to test the property lastProcessedAt
      //var instance = new Dora.CouponPayment();
      //expect(instance).to.be();
    });

  });

}));
