/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CouponPayment', function() {
      beforeEach(function() {
        instance = new Dora.CouponPayment();
      });

      it('should create an instance of CouponPayment', function() {
        // TODO: update the code to test CouponPayment
        expect(instance).to.be.a(Dora.CouponPayment);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property assetId (base name: "asset_id")', function() {
        // TODO: update the code to test the property assetId
        expect(instance).to.have.property('assetId');
        // expect(instance.assetId).to.be(expectedValueLiteral);
      });

      it('should have the property startAt (base name: "start_at")', function() {
        // TODO: update the code to test the property startAt
        expect(instance).to.have.property('startAt');
        // expect(instance.startAt).to.be(expectedValueLiteral);
      });

      it('should have the property payAt (base name: "pay_at")', function() {
        // TODO: update the code to test the property payAt
        expect(instance).to.have.property('payAt');
        // expect(instance.payAt).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property processedAt (base name: "processed_at")', function() {
        // TODO: update the code to test the property processedAt
        expect(instance).to.have.property('processedAt');
        // expect(instance.processedAt).to.be(expectedValueLiteral);
      });

      it('should have the property _yield (base name: "yield")', function() {
        // TODO: update the code to test the property _yield
        expect(instance).to.have.property('_yield');
        // expect(instance._yield).to.be(expectedValueLiteral);
      });

    });
  });

}));
