/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateOrderBookRequest', function() {
      beforeEach(function() {
        instance = new Dora.CreateOrderBookRequest();
      });

      it('should create an instance of CreateOrderBookRequest', function() {
        // TODO: update the code to test CreateOrderBookRequest
        expect(instance).to.be.a(Dora.CreateOrderBookRequest);
      });

      it('should have the property baseAssetId (base name: "base_asset_id")', function() {
        // TODO: update the code to test the property baseAssetId
        expect(instance).to.have.property('baseAssetId');
        // expect(instance.baseAssetId).to.be(expectedValueLiteral);
      });

      it('should have the property displayName (base name: "display_name")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property feeFactor (base name: "fee_factor")', function() {
        // TODO: update the code to test the property feeFactor
        expect(instance).to.have.property('feeFactor');
        // expect(instance.feeFactor).to.be(expectedValueLiteral);
      });

      it('should have the property initialAssetsRatio (base name: "initial_assets_ratio")', function() {
        // TODO: update the code to test the property initialAssetsRatio
        expect(instance).to.have.property('initialAssetsRatio');
        // expect(instance.initialAssetsRatio).to.be(expectedValueLiteral);
      });

      it('should have the property maturityAt (base name: "maturity_at")', function() {
        // TODO: update the code to test the property maturityAt
        expect(instance).to.have.property('maturityAt');
        // expect(instance.maturityAt).to.be(expectedValueLiteral);
      });

      it('should have the property priceDisplayMultiplier (base name: "price_display_multiplier")', function() {
        // TODO: update the code to test the property priceDisplayMultiplier
        expect(instance).to.have.property('priceDisplayMultiplier');
        // expect(instance.priceDisplayMultiplier).to.be(expectedValueLiteral);
      });

      it('should have the property quoteAssetId (base name: "quote_asset_id")', function() {
        // TODO: update the code to test the property quoteAssetId
        expect(instance).to.have.property('quoteAssetId');
        // expect(instance.quoteAssetId).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property tickSize (base name: "tick_size")', function() {
        // TODO: update the code to test the property tickSize
        expect(instance).to.have.property('tickSize');
        // expect(instance.tickSize).to.be(expectedValueLiteral);
      });

      it('should have the property baseQuantity (base name: "base_quantity")', function() {
        // TODO: update the code to test the property baseQuantity
        expect(instance).to.have.property('baseQuantity');
        // expect(instance.baseQuantity).to.be(expectedValueLiteral);
      });

      it('should have the property quoteQuantity (base name: "quote_quantity")', function() {
        // TODO: update the code to test the property quoteQuantity
        expect(instance).to.have.property('quoteQuantity');
        // expect(instance.quoteQuantity).to.be(expectedValueLiteral);
      });

      it('should have the property sharesAssetId (base name: "shares_asset_id")', function() {
        // TODO: update the code to test the property sharesAssetId
        expect(instance).to.have.property('sharesAssetId');
        // expect(instance.sharesAssetId).to.be(expectedValueLiteral);
      });

    });
  });

}));
