/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20015Data', function() {
      beforeEach(function() {
        instance = new Dora.InlineResponse20015Data();
      });

      it('should create an instance of InlineResponse20015Data', function() {
        // TODO: update the code to test InlineResponse20015Data
        expect(instance).to.be.a(Dora.InlineResponse20015Data);
      });

      it('should have the property cancelledOrderIds (base name: "cancelled_order_ids")', function() {
        // TODO: update the code to test the property cancelledOrderIds
        expect(instance).to.have.property('cancelledOrderIds');
        // expect(instance.cancelledOrderIds).to.be(expectedValueLiteral);
      });

    });
  });

}));
