/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dora.LeverageInterestRate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LeverageInterestRate', function() {
    it('should create an instance of LeverageInterestRate', function() {
      // uncomment below and update the code to test LeverageInterestRate
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be.a(Dora.LeverageInterestRate);
    });

    it('should have the property assetId (base name: "asset_id")', function() {
      // uncomment below and update the code to test the property assetId
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property utilization (base name: "utilization")', function() {
      // uncomment below and update the code to test the property utilization
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property avgUtilization (base name: "avg_utilization")', function() {
      // uncomment below and update the code to test the property avgUtilization
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property avgBorrowingYieldRate (base name: "avg_borrowing_yield_rate")', function() {
      // uncomment below and update the code to test the property avgBorrowingYieldRate
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property avgLendingYieldRate (base name: "avg_lending_yield_rate")', function() {
      // uncomment below and update the code to test the property avgLendingYieldRate
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property borrowingYieldRate (base name: "borrowing_yield_rate")', function() {
      // uncomment below and update the code to test the property borrowingYieldRate
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property lendingYieldRate (base name: "lending_yield_rate")', function() {
      // uncomment below and update the code to test the property lendingYieldRate
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property yieldToMaturity (base name: "yield_to_maturity")', function() {
      // uncomment below and update the code to test the property yieldToMaturity
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "start_time")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

    it('should have the property endTime (base name: "end_time")', function() {
      // uncomment below and update the code to test the property endTime
      //var instance = new Dora.LeverageInterestRate();
      //expect(instance).to.be();
    });

  });

}));
