/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModuleBalance', function() {
      beforeEach(function() {
        instance = new Dora.ModuleBalance();
      });

      it('should create an instance of ModuleBalance', function() {
        // TODO: update the code to test ModuleBalance
        expect(instance).to.be.a(Dora.ModuleBalance);
      });

      it('should have the property assetId (base name: "asset_id")', function() {
        // TODO: update the code to test the property assetId
        expect(instance).to.have.property('assetId');
        // expect(instance.assetId).to.be(expectedValueLiteral);
      });

      it('should have the property seq (base name: "seq")', function() {
        // TODO: update the code to test the property seq
        expect(instance).to.have.property('seq');
        // expect(instance.seq).to.be(expectedValueLiteral);
      });

      it('should have the property available (base name: "available")', function() {
        // TODO: update the code to test the property available
        expect(instance).to.have.property('available');
        // expect(instance.available).to.be(expectedValueLiteral);
      });

      it('should have the property supplied (base name: "supplied")', function() {
        // TODO: update the code to test the property supplied
        expect(instance).to.have.property('supplied');
        // expect(instance.supplied).to.be(expectedValueLiteral);
      });

      it('should have the property suppliedCollateral (base name: "supplied_collateral")', function() {
        // TODO: update the code to test the property suppliedCollateral
        expect(instance).to.have.property('suppliedCollateral');
        // expect(instance.suppliedCollateral).to.be(expectedValueLiteral);
      });

      it('should have the property virtual (base name: "virtual")', function() {
        // TODO: update the code to test the property virtual
        expect(instance).to.have.property('virtual');
        // expect(instance.virtual).to.be(expectedValueLiteral);
      });

      it('should have the property borrowed (base name: "borrowed")', function() {
        // TODO: update the code to test the property borrowed
        expect(instance).to.have.property('borrowed');
        // expect(instance.borrowed).to.be(expectedValueLiteral);
      });

    });
  });

}));
