/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('NewIsolatedPositionRequest', function() {
      beforeEach(function() {
        instance = new Dora.NewIsolatedPositionRequest();
      });

      it('should create an instance of NewIsolatedPositionRequest', function() {
        // TODO: update the code to test NewIsolatedPositionRequest
        expect(instance).to.be.a(Dora.NewIsolatedPositionRequest);
      });

      it('should have the property globalPositionId (base name: "global_position_id")', function() {
        // TODO: update the code to test the property globalPositionId
        expect(instance).to.have.property('globalPositionId');
        // expect(instance.globalPositionId).to.be(expectedValueLiteral);
      });

      it('should have the property assetId (base name: "asset_id")', function() {
        // TODO: update the code to test the property assetId
        expect(instance).to.have.property('assetId');
        // expect(instance.assetId).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property positionName (base name: "position_name")', function() {
        // TODO: update the code to test the property positionName
        expect(instance).to.have.property('positionName');
        // expect(instance.positionName).to.be(expectedValueLiteral);
      });

    });
  });

}));
