/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OrderbookStats', function() {
      beforeEach(function() {
        instance = new Dora.OrderbookStats();
      });

      it('should create an instance of OrderbookStats', function() {
        // TODO: update the code to test OrderbookStats
        expect(instance).to.be.a(Dora.OrderbookStats);
      });

      it('should have the property orderBookId (base name: "order_book_id")', function() {
        // TODO: update the code to test the property orderBookId
        expect(instance).to.have.property('orderBookId');
        // expect(instance.orderBookId).to.be(expectedValueLiteral);
      });

      it('should have the property openPrice (base name: "open_price")', function() {
        // TODO: update the code to test the property openPrice
        expect(instance).to.have.property('openPrice');
        // expect(instance.openPrice).to.be(expectedValueLiteral);
      });

      it('should have the property lastPrice (base name: "last_price")', function() {
        // TODO: update the code to test the property lastPrice
        expect(instance).to.have.property('lastPrice');
        // expect(instance.lastPrice).to.be(expectedValueLiteral);
      });

      it('should have the property high24h (base name: "high_24h")', function() {
        // TODO: update the code to test the property high24h
        expect(instance).to.have.property('high24h');
        // expect(instance.high24h).to.be(expectedValueLiteral);
      });

      it('should have the property low24h (base name: "low_24h")', function() {
        // TODO: update the code to test the property low24h
        expect(instance).to.have.property('low24h');
        // expect(instance.low24h).to.be(expectedValueLiteral);
      });

      it('should have the property change24h (base name: "change_24h")', function() {
        // TODO: update the code to test the property change24h
        expect(instance).to.have.property('change24h');
        // expect(instance.change24h).to.be(expectedValueLiteral);
      });

      it('should have the property changePct24h (base name: "change_pct_24h")', function() {
        // TODO: update the code to test the property changePct24h
        expect(instance).to.have.property('changePct24h');
        // expect(instance.changePct24h).to.be(expectedValueLiteral);
      });

      it('should have the property volume24hBase (base name: "volume_24h_base")', function() {
        // TODO: update the code to test the property volume24hBase
        expect(instance).to.have.property('volume24hBase');
        // expect(instance.volume24hBase).to.be(expectedValueLiteral);
      });

      it('should have the property volume24hUsd (base name: "volume_24h_usd")', function() {
        // TODO: update the code to test the property volume24hUsd
        expect(instance).to.have.property('volume24hUsd');
        // expect(instance.volume24hUsd).to.be(expectedValueLiteral);
      });

    });
  });

}));
