/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dora.PLAsset();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PLAsset', function() {
    it('should create an instance of PLAsset', function() {
      // uncomment below and update the code to test PLAsset
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be.a(Dora.PLAsset);
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property side (base name: "side")', function() {
      // uncomment below and update the code to test the property side
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property avgEntryPrice (base name: "avg_entry_price")', function() {
      // uncomment below and update the code to test the property avgEntryPrice
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property markPrice (base name: "mark_price")', function() {
      // uncomment below and update the code to test the property markPrice
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property liquidationPrice (base name: "liquidation_price")', function() {
      // uncomment below and update the code to test the property liquidationPrice
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property available (base name: "available")', function() {
      // uncomment below and update the code to test the property available
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property borrowed (base name: "borrowed")', function() {
      // uncomment below and update the code to test the property borrowed
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property margin (base name: "margin")', function() {
      // uncomment below and update the code to test the property margin
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property unrealizedPl (base name: "unrealized_pl")', function() {
      // uncomment below and update the code to test the property unrealizedPl
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property leverageLimit (base name: "leverage_limit")', function() {
      // uncomment below and update the code to test the property leverageLimit
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property tp (base name: "tp")', function() {
      // uncomment below and update the code to test the property tp
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property sl (base name: "sl")', function() {
      // uncomment below and update the code to test the property sl
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property initialCapital (base name: "initial_capital")', function() {
      // uncomment below and update the code to test the property initialCapital
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property impendingBorrows (base name: "impending_borrows")', function() {
      // uncomment below and update the code to test the property impendingBorrows
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property locked (base name: "locked")', function() {
      // uncomment below and update the code to test the property locked
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

    it('should have the property unusedCollateral (base name: "unused_collateral")', function() {
      // uncomment below and update the code to test the property unusedCollateral
      //var instance = new Dora.PLAsset();
      //expect(instance).to.be();
    });

  });

}));
