/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PLSummary', function() {
      beforeEach(function() {
        instance = new Dora.PLSummary();
      });

      it('should create an instance of PLSummary', function() {
        // TODO: update the code to test PLSummary
        expect(instance).to.be.a(Dora.PLSummary);
      });

      it('should have the property leverage (base name: "leverage")', function() {
        // TODO: update the code to test the property leverage
        expect(instance).to.have.property('leverage');
        // expect(instance.leverage).to.be(expectedValueLiteral);
      });

      it('should have the property accountEquity (base name: "account_equity")', function() {
        // TODO: update the code to test the property accountEquity
        expect(instance).to.have.property('accountEquity');
        // expect(instance.accountEquity).to.be(expectedValueLiteral);
      });

      it('should have the property available (base name: "available")', function() {
        // TODO: update the code to test the property available
        expect(instance).to.have.property('available');
        // expect(instance.available).to.be(expectedValueLiteral);
      });

      it('should have the property health (base name: "health")', function() {
        // TODO: update the code to test the property health
        expect(instance).to.have.property('health');
        // expect(instance.health).to.be(expectedValueLiteral);
      });

    });
  });

}));
