/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dora.PLSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PLSummary', function() {
    it('should create an instance of PLSummary', function() {
      // uncomment below and update the code to test PLSummary
      //var instance = new Dora.PLSummary();
      //expect(instance).to.be.a(Dora.PLSummary);
    });

    it('should have the property leverage (base name: "leverage")', function() {
      // uncomment below and update the code to test the property leverage
      //var instance = new Dora.PLSummary();
      //expect(instance).to.be();
    });

    it('should have the property accountEquity (base name: "account_equity")', function() {
      // uncomment below and update the code to test the property accountEquity
      //var instance = new Dora.PLSummary();
      //expect(instance).to.be();
    });

    it('should have the property available (base name: "available")', function() {
      // uncomment below and update the code to test the property available
      //var instance = new Dora.PLSummary();
      //expect(instance).to.be();
    });

    it('should have the property health (base name: "health")', function() {
      // uncomment below and update the code to test the property health
      //var instance = new Dora.PLSummary();
      //expect(instance).to.be();
    });

    it('should have the property ltv (base name: "ltv")', function() {
      // uncomment below and update the code to test the property ltv
      //var instance = new Dora.PLSummary();
      //expect(instance).to.be();
    });

  });

}));
