/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PoolPrice', function() {
      beforeEach(function() {
        instance = new Dora.PoolPrice();
      });

      it('should create an instance of PoolPrice', function() {
        // TODO: update the code to test PoolPrice
        expect(instance).to.be.a(Dora.PoolPrice);
      });

      it('should have the property poolId (base name: "pool_id")', function() {
        // TODO: update the code to test the property poolId
        expect(instance).to.have.property('poolId');
        // expect(instance.poolId).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

    });
  });

}));
