/*
 * DORA
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.69
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UpdateOrderBookRequest', function() {
      beforeEach(function() {
        instance = new Dora.UpdateOrderBookRequest();
      });

      it('should create an instance of UpdateOrderBookRequest', function() {
        // TODO: update the code to test UpdateOrderBookRequest
        expect(instance).to.be.a(Dora.UpdateOrderBookRequest);
      });

      it('should have the property orderBookId (base name: "order_book_id")', function() {
        // TODO: update the code to test the property orderBookId
        expect(instance).to.have.property('orderBookId');
        // expect(instance.orderBookId).to.be(expectedValueLiteral);
      });

      it('should have the property displayName (base name: "display_name")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property feeFactor (base name: "fee_factor")', function() {
        // TODO: update the code to test the property feeFactor
        expect(instance).to.have.property('feeFactor');
        // expect(instance.feeFactor).to.be(expectedValueLiteral);
      });

      it('should have the property initialAssetsRatio (base name: "initial_assets_ratio")', function() {
        // TODO: update the code to test the property initialAssetsRatio
        expect(instance).to.have.property('initialAssetsRatio');
        // expect(instance.initialAssetsRatio).to.be(expectedValueLiteral);
      });

      it('should have the property priceDisplayMultiplier (base name: "price_display_multiplier")', function() {
        // TODO: update the code to test the property priceDisplayMultiplier
        expect(instance).to.have.property('priceDisplayMultiplier');
        // expect(instance.priceDisplayMultiplier).to.be(expectedValueLiteral);
      });

      it('should have the property tickSize (base name: "tick_size")', function() {
        // TODO: update the code to test the property tickSize
        expect(instance).to.have.property('tickSize');
        // expect(instance.tickSize).to.be(expectedValueLiteral);
      });

      it('should have the property baseQuantity (base name: "base_quantity")', function() {
        // TODO: update the code to test the property baseQuantity
        expect(instance).to.have.property('baseQuantity');
        // expect(instance.baseQuantity).to.be(expectedValueLiteral);
      });

      it('should have the property quoteQuantity (base name: "quote_quantity")', function() {
        // TODO: update the code to test the property quoteQuantity
        expect(instance).to.have.property('quoteQuantity');
        // expect(instance.quoteQuantity).to.be(expectedValueLiteral);
      });

    });
  });

}));
