/**
 * DORA
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dora);
  }
}(this, function(expect, Dora) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dora.ValidateSubmitOrderRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ValidateSubmitOrderRequest', function() {
    it('should create an instance of ValidateSubmitOrderRequest', function() {
      // uncomment below and update the code to test ValidateSubmitOrderRequest
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be.a(Dora.ValidateSubmitOrderRequest);
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property tick (base name: "tick")', function() {
      // uncomment below and update the code to test the property tick
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property kind (base name: "kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property side (base name: "side")', function() {
      // uncomment below and update the code to test the property side
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property goodTillDate (base name: "good_till_date")', function() {
      // uncomment below and update the code to test the property goodTillDate
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property inverseLeverage (base name: "inverse_leverage")', function() {
      // uncomment below and update the code to test the property inverseLeverage
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property userBalance (base name: "user_balance")', function() {
      // uncomment below and update the code to test the property userBalance
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property baseAssetId (base name: "base_asset_id")', function() {
      // uncomment below and update the code to test the property baseAssetId
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property quoteAssetId (base name: "quote_asset_id")', function() {
      // uncomment below and update the code to test the property quoteAssetId
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property clientOrderId (base name: "client_order_id")', function() {
      // uncomment below and update the code to test the property clientOrderId
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property positionAssets (base name: "position_assets")', function() {
      // uncomment below and update the code to test the property positionAssets
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property assetsConfig (base name: "assets_config")', function() {
      // uncomment below and update the code to test the property assetsConfig
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property stopLossPrice (base name: "stop_loss_price")', function() {
      // uncomment below and update the code to test the property stopLossPrice
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property takeProfitPrice (base name: "take_profit_price")', function() {
      // uncomment below and update the code to test the property takeProfitPrice
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property restrictions (base name: "restrictions")', function() {
      // uncomment below and update the code to test the property restrictions
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property initialCapital (base name: "initial_capital")', function() {
      // uncomment below and update the code to test the property initialCapital
      //var instance = new Dora.ValidateSubmitOrderRequest();
      //expect(instance).to.be();
    });

  });

}));
